/*
 * Copyright 2019 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/conformance/storage/v1/tests.proto

package com.google.cloud.conformance.storage.v1;

public interface MethodOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.cloud.conformance.storage.v1.Method)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * e.g. storage.objects.get
   * </pre>
   *
   * <code>string name = 1;</code>
   *
   * @return The name.
   */
  java.lang.String getName();

  /**
   *
   *
   * <pre>
   * e.g. storage.objects.get
   * </pre>
   *
   * <code>string name = 1;</code>
   *
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString getNameBytes();

  /**
   * <code>repeated .google.cloud.conformance.storage.v1.Resource resources = 2;</code>
   *
   * @return A list containing the resources.
   */
  java.util.List<com.google.cloud.conformance.storage.v1.Resource> getResourcesList();

  /**
   * <code>repeated .google.cloud.conformance.storage.v1.Resource resources = 2;</code>
   *
   * @return The count of resources.
   */
  int getResourcesCount();

  /**
   * <code>repeated .google.cloud.conformance.storage.v1.Resource resources = 2;</code>
   *
   * @param index The index of the element to return.
   * @return The resources at the given index.
   */
  com.google.cloud.conformance.storage.v1.Resource getResources(int index);

  /**
   * <code>repeated .google.cloud.conformance.storage.v1.Resource resources = 2;</code>
   *
   * @return A list containing the enum numeric values on the wire for resources.
   */
  java.util.List<java.lang.Integer> getResourcesValueList();

  /**
   * <code>repeated .google.cloud.conformance.storage.v1.Resource resources = 2;</code>
   *
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of resources at the given index.
   */
  int getResourcesValue(int index);

  /**
   *
   *
   * <pre>
   * e.g. storage.resumable.upload
   * </pre>
   *
   * <code>string group = 3;</code>
   *
   * @return The group.
   */
  java.lang.String getGroup();

  /**
   *
   *
   * <pre>
   * e.g. storage.resumable.upload
   * </pre>
   *
   * <code>string group = 3;</code>
   *
   * @return The bytes for group.
   */
  com.google.protobuf.ByteString getGroupBytes();
}
