/*
 * Copyright 2019 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/conformance/storage/v1/tests.proto

package com.google.cloud.conformance.storage.v1;

public interface PolicyConditionsOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.cloud.conformance.storage.v1.PolicyConditions)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 contentLengthRange = 1;</code>
   *
   * @return A list containing the contentLengthRange.
   */
  java.util.List<java.lang.Integer> getContentLengthRangeList();
  /**
   * <code>repeated int32 contentLengthRange = 1;</code>
   *
   * @return The count of contentLengthRange.
   */
  int getContentLengthRangeCount();
  /**
   * <code>repeated int32 contentLengthRange = 1;</code>
   *
   * @param index The index of the element to return.
   * @return The contentLengthRange at the given index.
   */
  int getContentLengthRange(int index);

  /**
   * <code>repeated string startsWith = 2;</code>
   *
   * @return A list containing the startsWith.
   */
  java.util.List<java.lang.String> getStartsWithList();
  /**
   * <code>repeated string startsWith = 2;</code>
   *
   * @return The count of startsWith.
   */
  int getStartsWithCount();
  /**
   * <code>repeated string startsWith = 2;</code>
   *
   * @param index The index of the element to return.
   * @return The startsWith at the given index.
   */
  java.lang.String getStartsWith(int index);
  /**
   * <code>repeated string startsWith = 2;</code>
   *
   * @param index The index of the value to return.
   * @return The bytes of the startsWith at the given index.
   */
  com.google.protobuf.ByteString getStartsWithBytes(int index);
}
