/*
 * Copyright 2019 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/conformance/storage/v1/tests.proto

package com.google.cloud.conformance.storage.v1;

/** Protobuf type {@code google.cloud.conformance.storage.v1.PolicyInput} */
public final class PolicyInput extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:google.cloud.conformance.storage.v1.PolicyInput)
    PolicyInputOrBuilder {
  private static final long serialVersionUID = 0L;
  // Use PolicyInput.newBuilder() to construct.
  private PolicyInput(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private PolicyInput() {
    scheme_ = "";
    urlStyle_ = 0;
    bucketBoundHostname_ = "";
    bucket_ = "";
    object_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
    return new PolicyInput();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
    return this.unknownFields;
  }

  private PolicyInput(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10:
            {
              java.lang.String s = input.readStringRequireUtf8();

              scheme_ = s;
              break;
            }
          case 16:
            {
              int rawValue = input.readEnum();

              urlStyle_ = rawValue;
              break;
            }
          case 26:
            {
              java.lang.String s = input.readStringRequireUtf8();

              bucketBoundHostname_ = s;
              break;
            }
          case 34:
            {
              java.lang.String s = input.readStringRequireUtf8();

              bucket_ = s;
              break;
            }
          case 42:
            {
              java.lang.String s = input.readStringRequireUtf8();

              object_ = s;
              break;
            }
          case 48:
            {
              expiration_ = input.readInt32();
              break;
            }
          case 58:
            {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (timestamp_ != null) {
                subBuilder = timestamp_.toBuilder();
              }
              timestamp_ =
                  input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(timestamp_);
                timestamp_ = subBuilder.buildPartial();
              }

              break;
            }
          case 66:
            {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                fields_ =
                    com.google.protobuf.MapField.newMapField(FieldsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String> fields__ =
                  input.readMessage(
                      FieldsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              fields_.getMutableMap().put(fields__.getKey(), fields__.getValue());
              break;
            }
          case 74:
            {
              com.google.cloud.conformance.storage.v1.PolicyConditions.Builder subBuilder = null;
              if (conditions_ != null) {
                subBuilder = conditions_.toBuilder();
              }
              conditions_ =
                  input.readMessage(
                      com.google.cloud.conformance.storage.v1.PolicyConditions.parser(),
                      extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(conditions_);
                conditions_ = subBuilder.buildPartial();
              }

              break;
            }
          default:
            {
              if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return com.google.cloud.conformance.storage.v1.Tests
        .internal_static_google_cloud_conformance_storage_v1_PolicyInput_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(int number) {
    switch (number) {
      case 8:
        return internalGetFields();
      default:
        throw new RuntimeException("Invalid map field number: " + number);
    }
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.cloud.conformance.storage.v1.Tests
        .internal_static_google_cloud_conformance_storage_v1_PolicyInput_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.cloud.conformance.storage.v1.PolicyInput.class,
            com.google.cloud.conformance.storage.v1.PolicyInput.Builder.class);
  }

  public static final int SCHEME_FIELD_NUMBER = 1;
  private volatile java.lang.Object scheme_;
  /**
   * <code>string scheme = 1;</code>
   *
   * @return The scheme.
   */
  public java.lang.String getScheme() {
    java.lang.Object ref = scheme_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      scheme_ = s;
      return s;
    }
  }
  /**
   * <code>string scheme = 1;</code>
   *
   * @return The bytes for scheme.
   */
  public com.google.protobuf.ByteString getSchemeBytes() {
    java.lang.Object ref = scheme_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      scheme_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int URLSTYLE_FIELD_NUMBER = 2;
  private int urlStyle_;
  /**
   * <code>.google.cloud.conformance.storage.v1.UrlStyle urlStyle = 2;</code>
   *
   * @return The enum numeric value on the wire for urlStyle.
   */
  public int getUrlStyleValue() {
    return urlStyle_;
  }
  /**
   * <code>.google.cloud.conformance.storage.v1.UrlStyle urlStyle = 2;</code>
   *
   * @return The urlStyle.
   */
  public com.google.cloud.conformance.storage.v1.UrlStyle getUrlStyle() {
    @SuppressWarnings("deprecation")
    com.google.cloud.conformance.storage.v1.UrlStyle result =
        com.google.cloud.conformance.storage.v1.UrlStyle.valueOf(urlStyle_);
    return result == null ? com.google.cloud.conformance.storage.v1.UrlStyle.UNRECOGNIZED : result;
  }

  public static final int BUCKETBOUNDHOSTNAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object bucketBoundHostname_;
  /**
   * <code>string bucketBoundHostname = 3;</code>
   *
   * @return The bucketBoundHostname.
   */
  public java.lang.String getBucketBoundHostname() {
    java.lang.Object ref = bucketBoundHostname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bucketBoundHostname_ = s;
      return s;
    }
  }
  /**
   * <code>string bucketBoundHostname = 3;</code>
   *
   * @return The bytes for bucketBoundHostname.
   */
  public com.google.protobuf.ByteString getBucketBoundHostnameBytes() {
    java.lang.Object ref = bucketBoundHostname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      bucketBoundHostname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BUCKET_FIELD_NUMBER = 4;
  private volatile java.lang.Object bucket_;
  /**
   * <code>string bucket = 4;</code>
   *
   * @return The bucket.
   */
  public java.lang.String getBucket() {
    java.lang.Object ref = bucket_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bucket_ = s;
      return s;
    }
  }
  /**
   * <code>string bucket = 4;</code>
   *
   * @return The bytes for bucket.
   */
  public com.google.protobuf.ByteString getBucketBytes() {
    java.lang.Object ref = bucket_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      bucket_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OBJECT_FIELD_NUMBER = 5;
  private volatile java.lang.Object object_;
  /**
   * <code>string object = 5;</code>
   *
   * @return The object.
   */
  public java.lang.String getObject() {
    java.lang.Object ref = object_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      object_ = s;
      return s;
    }
  }
  /**
   * <code>string object = 5;</code>
   *
   * @return The bytes for object.
   */
  public com.google.protobuf.ByteString getObjectBytes() {
    java.lang.Object ref = object_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      object_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXPIRATION_FIELD_NUMBER = 6;
  private int expiration_;
  /**
   * <code>int32 expiration = 6;</code>
   *
   * @return The expiration.
   */
  public int getExpiration() {
    return expiration_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 7;
  private com.google.protobuf.Timestamp timestamp_;
  /**
   * <code>.google.protobuf.Timestamp timestamp = 7;</code>
   *
   * @return Whether the timestamp field is set.
   */
  public boolean hasTimestamp() {
    return timestamp_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp timestamp = 7;</code>
   *
   * @return The timestamp.
   */
  public com.google.protobuf.Timestamp getTimestamp() {
    return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
  }
  /** <code>.google.protobuf.Timestamp timestamp = 7;</code> */
  public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
    return getTimestamp();
  }

  public static final int FIELDS_FIELD_NUMBER = 8;

  private static final class FieldsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<java.lang.String, java.lang.String> defaultEntry =
        com.google.protobuf.MapEntry.<java.lang.String, java.lang.String>newDefaultInstance(
            com.google.cloud.conformance.storage.v1.Tests
                .internal_static_google_cloud_conformance_storage_v1_PolicyInput_FieldsEntry_descriptor,
            com.google.protobuf.WireFormat.FieldType.STRING,
            "",
            com.google.protobuf.WireFormat.FieldType.STRING,
            "");
  }

  private com.google.protobuf.MapField<java.lang.String, java.lang.String> fields_;

  private com.google.protobuf.MapField<java.lang.String, java.lang.String> internalGetFields() {
    if (fields_ == null) {
      return com.google.protobuf.MapField.emptyMapField(FieldsDefaultEntryHolder.defaultEntry);
    }
    return fields_;
  }

  public int getFieldsCount() {
    return internalGetFields().getMap().size();
  }
  /** <code>map&lt;string, string&gt; fields = 8;</code> */
  public boolean containsFields(java.lang.String key) {
    if (key == null) {
      throw new java.lang.NullPointerException();
    }
    return internalGetFields().getMap().containsKey(key);
  }
  /** Use {@link #getFieldsMap()} instead. */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getFields() {
    return getFieldsMap();
  }
  /** <code>map&lt;string, string&gt; fields = 8;</code> */
  public java.util.Map<java.lang.String, java.lang.String> getFieldsMap() {
    return internalGetFields().getMap();
  }
  /** <code>map&lt;string, string&gt; fields = 8;</code> */
  public java.lang.String getFieldsOrDefault(java.lang.String key, java.lang.String defaultValue) {
    if (key == null) {
      throw new java.lang.NullPointerException();
    }
    java.util.Map<java.lang.String, java.lang.String> map = internalGetFields().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /** <code>map&lt;string, string&gt; fields = 8;</code> */
  public java.lang.String getFieldsOrThrow(java.lang.String key) {
    if (key == null) {
      throw new java.lang.NullPointerException();
    }
    java.util.Map<java.lang.String, java.lang.String> map = internalGetFields().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int CONDITIONS_FIELD_NUMBER = 9;
  private com.google.cloud.conformance.storage.v1.PolicyConditions conditions_;
  /**
   * <code>.google.cloud.conformance.storage.v1.PolicyConditions conditions = 9;</code>
   *
   * @return Whether the conditions field is set.
   */
  public boolean hasConditions() {
    return conditions_ != null;
  }
  /**
   * <code>.google.cloud.conformance.storage.v1.PolicyConditions conditions = 9;</code>
   *
   * @return The conditions.
   */
  public com.google.cloud.conformance.storage.v1.PolicyConditions getConditions() {
    return conditions_ == null
        ? com.google.cloud.conformance.storage.v1.PolicyConditions.getDefaultInstance()
        : conditions_;
  }
  /** <code>.google.cloud.conformance.storage.v1.PolicyConditions conditions = 9;</code> */
  public com.google.cloud.conformance.storage.v1.PolicyConditionsOrBuilder
      getConditionsOrBuilder() {
    return getConditions();
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (!getSchemeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, scheme_);
    }
    if (urlStyle_ != com.google.cloud.conformance.storage.v1.UrlStyle.PATH_STYLE.getNumber()) {
      output.writeEnum(2, urlStyle_);
    }
    if (!getBucketBoundHostnameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, bucketBoundHostname_);
    }
    if (!getBucketBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, bucket_);
    }
    if (!getObjectBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, object_);
    }
    if (expiration_ != 0) {
      output.writeInt32(6, expiration_);
    }
    if (timestamp_ != null) {
      output.writeMessage(7, getTimestamp());
    }
    com.google.protobuf.GeneratedMessageV3.serializeStringMapTo(
        output, internalGetFields(), FieldsDefaultEntryHolder.defaultEntry, 8);
    if (conditions_ != null) {
      output.writeMessage(9, getConditions());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSchemeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, scheme_);
    }
    if (urlStyle_ != com.google.cloud.conformance.storage.v1.UrlStyle.PATH_STYLE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream.computeEnumSize(2, urlStyle_);
    }
    if (!getBucketBoundHostnameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, bucketBoundHostname_);
    }
    if (!getBucketBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, bucket_);
    }
    if (!getObjectBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, object_);
    }
    if (expiration_ != 0) {
      size += com.google.protobuf.CodedOutputStream.computeInt32Size(6, expiration_);
    }
    if (timestamp_ != null) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(7, getTimestamp());
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry :
        internalGetFields().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String> fields__ =
          FieldsDefaultEntryHolder.defaultEntry
              .newBuilderForType()
              .setKey(entry.getKey())
              .setValue(entry.getValue())
              .build();
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(8, fields__);
    }
    if (conditions_ != null) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(9, getConditions());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof com.google.cloud.conformance.storage.v1.PolicyInput)) {
      return super.equals(obj);
    }
    com.google.cloud.conformance.storage.v1.PolicyInput other =
        (com.google.cloud.conformance.storage.v1.PolicyInput) obj;

    if (!getScheme().equals(other.getScheme())) return false;
    if (urlStyle_ != other.urlStyle_) return false;
    if (!getBucketBoundHostname().equals(other.getBucketBoundHostname())) return false;
    if (!getBucket().equals(other.getBucket())) return false;
    if (!getObject().equals(other.getObject())) return false;
    if (getExpiration() != other.getExpiration()) return false;
    if (hasTimestamp() != other.hasTimestamp()) return false;
    if (hasTimestamp()) {
      if (!getTimestamp().equals(other.getTimestamp())) return false;
    }
    if (!internalGetFields().equals(other.internalGetFields())) return false;
    if (hasConditions() != other.hasConditions()) return false;
    if (hasConditions()) {
      if (!getConditions().equals(other.getConditions())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SCHEME_FIELD_NUMBER;
    hash = (53 * hash) + getScheme().hashCode();
    hash = (37 * hash) + URLSTYLE_FIELD_NUMBER;
    hash = (53 * hash) + urlStyle_;
    hash = (37 * hash) + BUCKETBOUNDHOSTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getBucketBoundHostname().hashCode();
    hash = (37 * hash) + BUCKET_FIELD_NUMBER;
    hash = (53 * hash) + getBucket().hashCode();
    hash = (37 * hash) + OBJECT_FIELD_NUMBER;
    hash = (53 * hash) + getObject().hashCode();
    hash = (37 * hash) + EXPIRATION_FIELD_NUMBER;
    hash = (53 * hash) + getExpiration();
    if (hasTimestamp()) {
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
    }
    if (!internalGetFields().getMap().isEmpty()) {
      hash = (37 * hash) + FIELDS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetFields().hashCode();
    }
    if (hasConditions()) {
      hash = (37 * hash) + CONDITIONS_FIELD_NUMBER;
      hash = (53 * hash) + getConditions().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.cloud.conformance.storage.v1.PolicyInput parseFrom(
      java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.cloud.conformance.storage.v1.PolicyInput parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.cloud.conformance.storage.v1.PolicyInput parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.cloud.conformance.storage.v1.PolicyInput parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.cloud.conformance.storage.v1.PolicyInput parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.cloud.conformance.storage.v1.PolicyInput parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.cloud.conformance.storage.v1.PolicyInput parseFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.google.cloud.conformance.storage.v1.PolicyInput parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.google.cloud.conformance.storage.v1.PolicyInput parseDelimitedFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.cloud.conformance.storage.v1.PolicyInput parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.google.cloud.conformance.storage.v1.PolicyInput parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.google.cloud.conformance.storage.v1.PolicyInput parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(com.google.cloud.conformance.storage.v1.PolicyInput prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /** Protobuf type {@code google.cloud.conformance.storage.v1.PolicyInput} */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:google.cloud.conformance.storage.v1.PolicyInput)
      com.google.cloud.conformance.storage.v1.PolicyInputOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.google.cloud.conformance.storage.v1.Tests
          .internal_static_google_cloud_conformance_storage_v1_PolicyInput_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(int number) {
      switch (number) {
        case 8:
          return internalGetFields();
        default:
          throw new RuntimeException("Invalid map field number: " + number);
      }
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(int number) {
      switch (number) {
        case 8:
          return internalGetMutableFields();
        default:
          throw new RuntimeException("Invalid map field number: " + number);
      }
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.cloud.conformance.storage.v1.Tests
          .internal_static_google_cloud_conformance_storage_v1_PolicyInput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.cloud.conformance.storage.v1.PolicyInput.class,
              com.google.cloud.conformance.storage.v1.PolicyInput.Builder.class);
    }

    // Construct using com.google.cloud.conformance.storage.v1.PolicyInput.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {}
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      scheme_ = "";

      urlStyle_ = 0;

      bucketBoundHostname_ = "";

      bucket_ = "";

      object_ = "";

      expiration_ = 0;

      if (timestampBuilder_ == null) {
        timestamp_ = null;
      } else {
        timestamp_ = null;
        timestampBuilder_ = null;
      }
      internalGetMutableFields().clear();
      if (conditionsBuilder_ == null) {
        conditions_ = null;
      } else {
        conditions_ = null;
        conditionsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return com.google.cloud.conformance.storage.v1.Tests
          .internal_static_google_cloud_conformance_storage_v1_PolicyInput_descriptor;
    }

    @java.lang.Override
    public com.google.cloud.conformance.storage.v1.PolicyInput getDefaultInstanceForType() {
      return com.google.cloud.conformance.storage.v1.PolicyInput.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.cloud.conformance.storage.v1.PolicyInput build() {
      com.google.cloud.conformance.storage.v1.PolicyInput result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.cloud.conformance.storage.v1.PolicyInput buildPartial() {
      com.google.cloud.conformance.storage.v1.PolicyInput result =
          new com.google.cloud.conformance.storage.v1.PolicyInput(this);
      int from_bitField0_ = bitField0_;
      result.scheme_ = scheme_;
      result.urlStyle_ = urlStyle_;
      result.bucketBoundHostname_ = bucketBoundHostname_;
      result.bucket_ = bucket_;
      result.object_ = object_;
      result.expiration_ = expiration_;
      if (timestampBuilder_ == null) {
        result.timestamp_ = timestamp_;
      } else {
        result.timestamp_ = timestampBuilder_.build();
      }
      result.fields_ = internalGetFields();
      result.fields_.makeImmutable();
      if (conditionsBuilder_ == null) {
        result.conditions_ = conditions_;
      } else {
        result.conditions_ = conditionsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.cloud.conformance.storage.v1.PolicyInput) {
        return mergeFrom((com.google.cloud.conformance.storage.v1.PolicyInput) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.cloud.conformance.storage.v1.PolicyInput other) {
      if (other == com.google.cloud.conformance.storage.v1.PolicyInput.getDefaultInstance())
        return this;
      if (!other.getScheme().isEmpty()) {
        scheme_ = other.scheme_;
        onChanged();
      }
      if (other.urlStyle_ != 0) {
        setUrlStyleValue(other.getUrlStyleValue());
      }
      if (!other.getBucketBoundHostname().isEmpty()) {
        bucketBoundHostname_ = other.bucketBoundHostname_;
        onChanged();
      }
      if (!other.getBucket().isEmpty()) {
        bucket_ = other.bucket_;
        onChanged();
      }
      if (!other.getObject().isEmpty()) {
        object_ = other.object_;
        onChanged();
      }
      if (other.getExpiration() != 0) {
        setExpiration(other.getExpiration());
      }
      if (other.hasTimestamp()) {
        mergeTimestamp(other.getTimestamp());
      }
      internalGetMutableFields().mergeFrom(other.internalGetFields());
      if (other.hasConditions()) {
        mergeConditions(other.getConditions());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.cloud.conformance.storage.v1.PolicyInput parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage =
            (com.google.cloud.conformance.storage.v1.PolicyInput) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int bitField0_;

    private java.lang.Object scheme_ = "";
    /**
     * <code>string scheme = 1;</code>
     *
     * @return The scheme.
     */
    public java.lang.String getScheme() {
      java.lang.Object ref = scheme_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        scheme_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string scheme = 1;</code>
     *
     * @return The bytes for scheme.
     */
    public com.google.protobuf.ByteString getSchemeBytes() {
      java.lang.Object ref = scheme_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        scheme_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string scheme = 1;</code>
     *
     * @param value The scheme to set.
     * @return This builder for chaining.
     */
    public Builder setScheme(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      scheme_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string scheme = 1;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearScheme() {

      scheme_ = getDefaultInstance().getScheme();
      onChanged();
      return this;
    }
    /**
     * <code>string scheme = 1;</code>
     *
     * @param value The bytes for scheme to set.
     * @return This builder for chaining.
     */
    public Builder setSchemeBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      scheme_ = value;
      onChanged();
      return this;
    }

    private int urlStyle_ = 0;
    /**
     * <code>.google.cloud.conformance.storage.v1.UrlStyle urlStyle = 2;</code>
     *
     * @return The enum numeric value on the wire for urlStyle.
     */
    public int getUrlStyleValue() {
      return urlStyle_;
    }
    /**
     * <code>.google.cloud.conformance.storage.v1.UrlStyle urlStyle = 2;</code>
     *
     * @param value The enum numeric value on the wire for urlStyle to set.
     * @return This builder for chaining.
     */
    public Builder setUrlStyleValue(int value) {
      urlStyle_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.google.cloud.conformance.storage.v1.UrlStyle urlStyle = 2;</code>
     *
     * @return The urlStyle.
     */
    public com.google.cloud.conformance.storage.v1.UrlStyle getUrlStyle() {
      @SuppressWarnings("deprecation")
      com.google.cloud.conformance.storage.v1.UrlStyle result =
          com.google.cloud.conformance.storage.v1.UrlStyle.valueOf(urlStyle_);
      return result == null
          ? com.google.cloud.conformance.storage.v1.UrlStyle.UNRECOGNIZED
          : result;
    }
    /**
     * <code>.google.cloud.conformance.storage.v1.UrlStyle urlStyle = 2;</code>
     *
     * @param value The urlStyle to set.
     * @return This builder for chaining.
     */
    public Builder setUrlStyle(com.google.cloud.conformance.storage.v1.UrlStyle value) {
      if (value == null) {
        throw new NullPointerException();
      }

      urlStyle_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.google.cloud.conformance.storage.v1.UrlStyle urlStyle = 2;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearUrlStyle() {

      urlStyle_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object bucketBoundHostname_ = "";
    /**
     * <code>string bucketBoundHostname = 3;</code>
     *
     * @return The bucketBoundHostname.
     */
    public java.lang.String getBucketBoundHostname() {
      java.lang.Object ref = bucketBoundHostname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bucketBoundHostname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string bucketBoundHostname = 3;</code>
     *
     * @return The bytes for bucketBoundHostname.
     */
    public com.google.protobuf.ByteString getBucketBoundHostnameBytes() {
      java.lang.Object ref = bucketBoundHostname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        bucketBoundHostname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string bucketBoundHostname = 3;</code>
     *
     * @param value The bucketBoundHostname to set.
     * @return This builder for chaining.
     */
    public Builder setBucketBoundHostname(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      bucketBoundHostname_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string bucketBoundHostname = 3;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearBucketBoundHostname() {

      bucketBoundHostname_ = getDefaultInstance().getBucketBoundHostname();
      onChanged();
      return this;
    }
    /**
     * <code>string bucketBoundHostname = 3;</code>
     *
     * @param value The bytes for bucketBoundHostname to set.
     * @return This builder for chaining.
     */
    public Builder setBucketBoundHostnameBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      bucketBoundHostname_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object bucket_ = "";
    /**
     * <code>string bucket = 4;</code>
     *
     * @return The bucket.
     */
    public java.lang.String getBucket() {
      java.lang.Object ref = bucket_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bucket_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string bucket = 4;</code>
     *
     * @return The bytes for bucket.
     */
    public com.google.protobuf.ByteString getBucketBytes() {
      java.lang.Object ref = bucket_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        bucket_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string bucket = 4;</code>
     *
     * @param value The bucket to set.
     * @return This builder for chaining.
     */
    public Builder setBucket(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      bucket_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string bucket = 4;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearBucket() {

      bucket_ = getDefaultInstance().getBucket();
      onChanged();
      return this;
    }
    /**
     * <code>string bucket = 4;</code>
     *
     * @param value The bytes for bucket to set.
     * @return This builder for chaining.
     */
    public Builder setBucketBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      bucket_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object object_ = "";
    /**
     * <code>string object = 5;</code>
     *
     * @return The object.
     */
    public java.lang.String getObject() {
      java.lang.Object ref = object_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        object_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string object = 5;</code>
     *
     * @return The bytes for object.
     */
    public com.google.protobuf.ByteString getObjectBytes() {
      java.lang.Object ref = object_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        object_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string object = 5;</code>
     *
     * @param value The object to set.
     * @return This builder for chaining.
     */
    public Builder setObject(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      object_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string object = 5;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearObject() {

      object_ = getDefaultInstance().getObject();
      onChanged();
      return this;
    }
    /**
     * <code>string object = 5;</code>
     *
     * @param value The bytes for object to set.
     * @return This builder for chaining.
     */
    public Builder setObjectBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      object_ = value;
      onChanged();
      return this;
    }

    private int expiration_;
    /**
     * <code>int32 expiration = 6;</code>
     *
     * @return The expiration.
     */
    public int getExpiration() {
      return expiration_;
    }
    /**
     * <code>int32 expiration = 6;</code>
     *
     * @param value The expiration to set.
     * @return This builder for chaining.
     */
    public Builder setExpiration(int value) {

      expiration_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 expiration = 6;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearExpiration() {

      expiration_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp timestamp_;
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp,
            com.google.protobuf.Timestamp.Builder,
            com.google.protobuf.TimestampOrBuilder>
        timestampBuilder_;
    /**
     * <code>.google.protobuf.Timestamp timestamp = 7;</code>
     *
     * @return Whether the timestamp field is set.
     */
    public boolean hasTimestamp() {
      return timestampBuilder_ != null || timestamp_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 7;</code>
     *
     * @return The timestamp.
     */
    public com.google.protobuf.Timestamp getTimestamp() {
      if (timestampBuilder_ == null) {
        return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      } else {
        return timestampBuilder_.getMessage();
      }
    }
    /** <code>.google.protobuf.Timestamp timestamp = 7;</code> */
    public Builder setTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timestamp_ = value;
        onChanged();
      } else {
        timestampBuilder_.setMessage(value);
      }

      return this;
    }
    /** <code>.google.protobuf.Timestamp timestamp = 7;</code> */
    public Builder setTimestamp(com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timestampBuilder_ == null) {
        timestamp_ = builderForValue.build();
        onChanged();
      } else {
        timestampBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /** <code>.google.protobuf.Timestamp timestamp = 7;</code> */
    public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (timestamp_ != null) {
          timestamp_ =
              com.google.protobuf.Timestamp.newBuilder(timestamp_).mergeFrom(value).buildPartial();
        } else {
          timestamp_ = value;
        }
        onChanged();
      } else {
        timestampBuilder_.mergeFrom(value);
      }

      return this;
    }
    /** <code>.google.protobuf.Timestamp timestamp = 7;</code> */
    public Builder clearTimestamp() {
      if (timestampBuilder_ == null) {
        timestamp_ = null;
        onChanged();
      } else {
        timestamp_ = null;
        timestampBuilder_ = null;
      }

      return this;
    }
    /** <code>.google.protobuf.Timestamp timestamp = 7;</code> */
    public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {

      onChanged();
      return getTimestampFieldBuilder().getBuilder();
    }
    /** <code>.google.protobuf.Timestamp timestamp = 7;</code> */
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      if (timestampBuilder_ != null) {
        return timestampBuilder_.getMessageOrBuilder();
      } else {
        return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      }
    }
    /** <code>.google.protobuf.Timestamp timestamp = 7;</code> */
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp,
            com.google.protobuf.Timestamp.Builder,
            com.google.protobuf.TimestampOrBuilder>
        getTimestampFieldBuilder() {
      if (timestampBuilder_ == null) {
        timestampBuilder_ =
            new com.google.protobuf.SingleFieldBuilderV3<
                com.google.protobuf.Timestamp,
                com.google.protobuf.Timestamp.Builder,
                com.google.protobuf.TimestampOrBuilder>(
                getTimestamp(), getParentForChildren(), isClean());
        timestamp_ = null;
      }
      return timestampBuilder_;
    }

    private com.google.protobuf.MapField<java.lang.String, java.lang.String> fields_;

    private com.google.protobuf.MapField<java.lang.String, java.lang.String> internalGetFields() {
      if (fields_ == null) {
        return com.google.protobuf.MapField.emptyMapField(FieldsDefaultEntryHolder.defaultEntry);
      }
      return fields_;
    }

    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableFields() {
      onChanged();
      ;
      if (fields_ == null) {
        fields_ = com.google.protobuf.MapField.newMapField(FieldsDefaultEntryHolder.defaultEntry);
      }
      if (!fields_.isMutable()) {
        fields_ = fields_.copy();
      }
      return fields_;
    }

    public int getFieldsCount() {
      return internalGetFields().getMap().size();
    }
    /** <code>map&lt;string, string&gt; fields = 8;</code> */
    public boolean containsFields(java.lang.String key) {
      if (key == null) {
        throw new java.lang.NullPointerException();
      }
      return internalGetFields().getMap().containsKey(key);
    }
    /** Use {@link #getFieldsMap()} instead. */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getFields() {
      return getFieldsMap();
    }
    /** <code>map&lt;string, string&gt; fields = 8;</code> */
    public java.util.Map<java.lang.String, java.lang.String> getFieldsMap() {
      return internalGetFields().getMap();
    }
    /** <code>map&lt;string, string&gt; fields = 8;</code> */
    public java.lang.String getFieldsOrDefault(
        java.lang.String key, java.lang.String defaultValue) {
      if (key == null) {
        throw new java.lang.NullPointerException();
      }
      java.util.Map<java.lang.String, java.lang.String> map = internalGetFields().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /** <code>map&lt;string, string&gt; fields = 8;</code> */
    public java.lang.String getFieldsOrThrow(java.lang.String key) {
      if (key == null) {
        throw new java.lang.NullPointerException();
      }
      java.util.Map<java.lang.String, java.lang.String> map = internalGetFields().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearFields() {
      internalGetMutableFields().getMutableMap().clear();
      return this;
    }
    /** <code>map&lt;string, string&gt; fields = 8;</code> */
    public Builder removeFields(java.lang.String key) {
      if (key == null) {
        throw new java.lang.NullPointerException();
      }
      internalGetMutableFields().getMutableMap().remove(key);
      return this;
    }
    /** Use alternate mutation accessors instead. */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMutableFields() {
      return internalGetMutableFields().getMutableMap();
    }
    /** <code>map&lt;string, string&gt; fields = 8;</code> */
    public Builder putFields(java.lang.String key, java.lang.String value) {
      if (key == null) {
        throw new java.lang.NullPointerException();
      }
      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      internalGetMutableFields().getMutableMap().put(key, value);
      return this;
    }
    /** <code>map&lt;string, string&gt; fields = 8;</code> */
    public Builder putAllFields(java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableFields().getMutableMap().putAll(values);
      return this;
    }

    private com.google.cloud.conformance.storage.v1.PolicyConditions conditions_;
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.cloud.conformance.storage.v1.PolicyConditions,
            com.google.cloud.conformance.storage.v1.PolicyConditions.Builder,
            com.google.cloud.conformance.storage.v1.PolicyConditionsOrBuilder>
        conditionsBuilder_;
    /**
     * <code>.google.cloud.conformance.storage.v1.PolicyConditions conditions = 9;</code>
     *
     * @return Whether the conditions field is set.
     */
    public boolean hasConditions() {
      return conditionsBuilder_ != null || conditions_ != null;
    }
    /**
     * <code>.google.cloud.conformance.storage.v1.PolicyConditions conditions = 9;</code>
     *
     * @return The conditions.
     */
    public com.google.cloud.conformance.storage.v1.PolicyConditions getConditions() {
      if (conditionsBuilder_ == null) {
        return conditions_ == null
            ? com.google.cloud.conformance.storage.v1.PolicyConditions.getDefaultInstance()
            : conditions_;
      } else {
        return conditionsBuilder_.getMessage();
      }
    }
    /** <code>.google.cloud.conformance.storage.v1.PolicyConditions conditions = 9;</code> */
    public Builder setConditions(com.google.cloud.conformance.storage.v1.PolicyConditions value) {
      if (conditionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        conditions_ = value;
        onChanged();
      } else {
        conditionsBuilder_.setMessage(value);
      }

      return this;
    }
    /** <code>.google.cloud.conformance.storage.v1.PolicyConditions conditions = 9;</code> */
    public Builder setConditions(
        com.google.cloud.conformance.storage.v1.PolicyConditions.Builder builderForValue) {
      if (conditionsBuilder_ == null) {
        conditions_ = builderForValue.build();
        onChanged();
      } else {
        conditionsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /** <code>.google.cloud.conformance.storage.v1.PolicyConditions conditions = 9;</code> */
    public Builder mergeConditions(com.google.cloud.conformance.storage.v1.PolicyConditions value) {
      if (conditionsBuilder_ == null) {
        if (conditions_ != null) {
          conditions_ =
              com.google.cloud.conformance.storage.v1.PolicyConditions.newBuilder(conditions_)
                  .mergeFrom(value)
                  .buildPartial();
        } else {
          conditions_ = value;
        }
        onChanged();
      } else {
        conditionsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /** <code>.google.cloud.conformance.storage.v1.PolicyConditions conditions = 9;</code> */
    public Builder clearConditions() {
      if (conditionsBuilder_ == null) {
        conditions_ = null;
        onChanged();
      } else {
        conditions_ = null;
        conditionsBuilder_ = null;
      }

      return this;
    }
    /** <code>.google.cloud.conformance.storage.v1.PolicyConditions conditions = 9;</code> */
    public com.google.cloud.conformance.storage.v1.PolicyConditions.Builder getConditionsBuilder() {

      onChanged();
      return getConditionsFieldBuilder().getBuilder();
    }
    /** <code>.google.cloud.conformance.storage.v1.PolicyConditions conditions = 9;</code> */
    public com.google.cloud.conformance.storage.v1.PolicyConditionsOrBuilder
        getConditionsOrBuilder() {
      if (conditionsBuilder_ != null) {
        return conditionsBuilder_.getMessageOrBuilder();
      } else {
        return conditions_ == null
            ? com.google.cloud.conformance.storage.v1.PolicyConditions.getDefaultInstance()
            : conditions_;
      }
    }
    /** <code>.google.cloud.conformance.storage.v1.PolicyConditions conditions = 9;</code> */
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.cloud.conformance.storage.v1.PolicyConditions,
            com.google.cloud.conformance.storage.v1.PolicyConditions.Builder,
            com.google.cloud.conformance.storage.v1.PolicyConditionsOrBuilder>
        getConditionsFieldBuilder() {
      if (conditionsBuilder_ == null) {
        conditionsBuilder_ =
            new com.google.protobuf.SingleFieldBuilderV3<
                com.google.cloud.conformance.storage.v1.PolicyConditions,
                com.google.cloud.conformance.storage.v1.PolicyConditions.Builder,
                com.google.cloud.conformance.storage.v1.PolicyConditionsOrBuilder>(
                getConditions(), getParentForChildren(), isClean());
        conditions_ = null;
      }
      return conditionsBuilder_;
    }

    @java.lang.Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:google.cloud.conformance.storage.v1.PolicyInput)
  }

  // @@protoc_insertion_point(class_scope:google.cloud.conformance.storage.v1.PolicyInput)
  private static final com.google.cloud.conformance.storage.v1.PolicyInput DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new com.google.cloud.conformance.storage.v1.PolicyInput();
  }

  public static com.google.cloud.conformance.storage.v1.PolicyInput getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PolicyInput> PARSER =
      new com.google.protobuf.AbstractParser<PolicyInput>() {
        @java.lang.Override
        public PolicyInput parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new PolicyInput(input, extensionRegistry);
        }
      };

  public static com.google.protobuf.Parser<PolicyInput> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PolicyInput> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.cloud.conformance.storage.v1.PolicyInput getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
