/*
 * Copyright 2019 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/conformance/storage/v1/tests.proto

package com.google.cloud.conformance.storage.v1;

/** Protobuf type {@code google.cloud.conformance.storage.v1.PolicyConditions} */
public final class PolicyConditions extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:google.cloud.conformance.storage.v1.PolicyConditions)
    PolicyConditionsOrBuilder {
  private static final long serialVersionUID = 0L;
  // Use PolicyConditions.newBuilder() to construct.
  private PolicyConditions(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private PolicyConditions() {
    successActionStatus_ = "";
    successActionRedirect_ = "";
    matches_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
    return new PolicyConditions();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
    return this.unknownFields;
  }

  private PolicyConditions(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10:
            {
              java.lang.String s = input.readStringRequireUtf8();

              successActionStatus_ = s;
              break;
            }
          case 18:
            {
              java.lang.String s = input.readStringRequireUtf8();

              successActionRedirect_ = s;
              break;
            }
          case 26:
            {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                matches_ =
                    new java.util.ArrayList<
                        com.google.cloud.conformance.storage.v1.ConditionalMatches>();
                mutable_bitField0_ |= 0x00000001;
              }
              matches_.add(
                  input.readMessage(
                      com.google.cloud.conformance.storage.v1.ConditionalMatches.parser(),
                      extensionRegistry));
              break;
            }
          default:
            {
              if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        matches_ = java.util.Collections.unmodifiableList(matches_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return com.google.cloud.conformance.storage.v1.Tests
        .internal_static_google_cloud_conformance_storage_v1_PolicyConditions_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.cloud.conformance.storage.v1.Tests
        .internal_static_google_cloud_conformance_storage_v1_PolicyConditions_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.cloud.conformance.storage.v1.PolicyConditions.class,
            com.google.cloud.conformance.storage.v1.PolicyConditions.Builder.class);
  }

  public static final int SUCCESSACTIONSTATUS_FIELD_NUMBER = 1;
  private volatile java.lang.Object successActionStatus_;
  /**
   * <code>string successActionStatus = 1;</code>
   *
   * @return The successActionStatus.
   */
  public java.lang.String getSuccessActionStatus() {
    java.lang.Object ref = successActionStatus_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      successActionStatus_ = s;
      return s;
    }
  }
  /**
   * <code>string successActionStatus = 1;</code>
   *
   * @return The bytes for successActionStatus.
   */
  public com.google.protobuf.ByteString getSuccessActionStatusBytes() {
    java.lang.Object ref = successActionStatus_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      successActionStatus_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUCCESSACTIONREDIRECT_FIELD_NUMBER = 2;
  private volatile java.lang.Object successActionRedirect_;
  /**
   * <code>string successActionRedirect = 2;</code>
   *
   * @return The successActionRedirect.
   */
  public java.lang.String getSuccessActionRedirect() {
    java.lang.Object ref = successActionRedirect_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      successActionRedirect_ = s;
      return s;
    }
  }
  /**
   * <code>string successActionRedirect = 2;</code>
   *
   * @return The bytes for successActionRedirect.
   */
  public com.google.protobuf.ByteString getSuccessActionRedirectBytes() {
    java.lang.Object ref = successActionRedirect_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      successActionRedirect_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MATCHES_FIELD_NUMBER = 3;
  private java.util.List<com.google.cloud.conformance.storage.v1.ConditionalMatches> matches_;
  /** <code>repeated .google.cloud.conformance.storage.v1.ConditionalMatches matches = 3;</code> */
  public java.util.List<com.google.cloud.conformance.storage.v1.ConditionalMatches>
      getMatchesList() {
    return matches_;
  }
  /** <code>repeated .google.cloud.conformance.storage.v1.ConditionalMatches matches = 3;</code> */
  public java.util.List<
          ? extends com.google.cloud.conformance.storage.v1.ConditionalMatchesOrBuilder>
      getMatchesOrBuilderList() {
    return matches_;
  }
  /** <code>repeated .google.cloud.conformance.storage.v1.ConditionalMatches matches = 3;</code> */
  public int getMatchesCount() {
    return matches_.size();
  }
  /** <code>repeated .google.cloud.conformance.storage.v1.ConditionalMatches matches = 3;</code> */
  public com.google.cloud.conformance.storage.v1.ConditionalMatches getMatches(int index) {
    return matches_.get(index);
  }
  /** <code>repeated .google.cloud.conformance.storage.v1.ConditionalMatches matches = 3;</code> */
  public com.google.cloud.conformance.storage.v1.ConditionalMatchesOrBuilder getMatchesOrBuilder(
      int index) {
    return matches_.get(index);
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (!getSuccessActionStatusBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, successActionStatus_);
    }
    if (!getSuccessActionRedirectBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, successActionRedirect_);
    }
    for (int i = 0; i < matches_.size(); i++) {
      output.writeMessage(3, matches_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSuccessActionStatusBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, successActionStatus_);
    }
    if (!getSuccessActionRedirectBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, successActionRedirect_);
    }
    for (int i = 0; i < matches_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(3, matches_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof com.google.cloud.conformance.storage.v1.PolicyConditions)) {
      return super.equals(obj);
    }
    com.google.cloud.conformance.storage.v1.PolicyConditions other =
        (com.google.cloud.conformance.storage.v1.PolicyConditions) obj;

    if (!getSuccessActionStatus().equals(other.getSuccessActionStatus())) return false;
    if (!getSuccessActionRedirect().equals(other.getSuccessActionRedirect())) return false;
    if (!getMatchesList().equals(other.getMatchesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUCCESSACTIONSTATUS_FIELD_NUMBER;
    hash = (53 * hash) + getSuccessActionStatus().hashCode();
    hash = (37 * hash) + SUCCESSACTIONREDIRECT_FIELD_NUMBER;
    hash = (53 * hash) + getSuccessActionRedirect().hashCode();
    if (getMatchesCount() > 0) {
      hash = (37 * hash) + MATCHES_FIELD_NUMBER;
      hash = (53 * hash) + getMatchesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.cloud.conformance.storage.v1.PolicyConditions parseFrom(
      java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.cloud.conformance.storage.v1.PolicyConditions parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.cloud.conformance.storage.v1.PolicyConditions parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.cloud.conformance.storage.v1.PolicyConditions parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.cloud.conformance.storage.v1.PolicyConditions parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.cloud.conformance.storage.v1.PolicyConditions parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.cloud.conformance.storage.v1.PolicyConditions parseFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.google.cloud.conformance.storage.v1.PolicyConditions parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.google.cloud.conformance.storage.v1.PolicyConditions parseDelimitedFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.cloud.conformance.storage.v1.PolicyConditions parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.google.cloud.conformance.storage.v1.PolicyConditions parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.google.cloud.conformance.storage.v1.PolicyConditions parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(
      com.google.cloud.conformance.storage.v1.PolicyConditions prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /** Protobuf type {@code google.cloud.conformance.storage.v1.PolicyConditions} */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:google.cloud.conformance.storage.v1.PolicyConditions)
      com.google.cloud.conformance.storage.v1.PolicyConditionsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.google.cloud.conformance.storage.v1.Tests
          .internal_static_google_cloud_conformance_storage_v1_PolicyConditions_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.cloud.conformance.storage.v1.Tests
          .internal_static_google_cloud_conformance_storage_v1_PolicyConditions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.cloud.conformance.storage.v1.PolicyConditions.class,
              com.google.cloud.conformance.storage.v1.PolicyConditions.Builder.class);
    }

    // Construct using com.google.cloud.conformance.storage.v1.PolicyConditions.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
        getMatchesFieldBuilder();
      }
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      successActionStatus_ = "";

      successActionRedirect_ = "";

      if (matchesBuilder_ == null) {
        matches_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        matchesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return com.google.cloud.conformance.storage.v1.Tests
          .internal_static_google_cloud_conformance_storage_v1_PolicyConditions_descriptor;
    }

    @java.lang.Override
    public com.google.cloud.conformance.storage.v1.PolicyConditions getDefaultInstanceForType() {
      return com.google.cloud.conformance.storage.v1.PolicyConditions.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.cloud.conformance.storage.v1.PolicyConditions build() {
      com.google.cloud.conformance.storage.v1.PolicyConditions result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.cloud.conformance.storage.v1.PolicyConditions buildPartial() {
      com.google.cloud.conformance.storage.v1.PolicyConditions result =
          new com.google.cloud.conformance.storage.v1.PolicyConditions(this);
      int from_bitField0_ = bitField0_;
      result.successActionStatus_ = successActionStatus_;
      result.successActionRedirect_ = successActionRedirect_;
      if (matchesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          matches_ = java.util.Collections.unmodifiableList(matches_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.matches_ = matches_;
      } else {
        result.matches_ = matchesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.cloud.conformance.storage.v1.PolicyConditions) {
        return mergeFrom((com.google.cloud.conformance.storage.v1.PolicyConditions) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.cloud.conformance.storage.v1.PolicyConditions other) {
      if (other == com.google.cloud.conformance.storage.v1.PolicyConditions.getDefaultInstance())
        return this;
      if (!other.getSuccessActionStatus().isEmpty()) {
        successActionStatus_ = other.successActionStatus_;
        onChanged();
      }
      if (!other.getSuccessActionRedirect().isEmpty()) {
        successActionRedirect_ = other.successActionRedirect_;
        onChanged();
      }
      if (matchesBuilder_ == null) {
        if (!other.matches_.isEmpty()) {
          if (matches_.isEmpty()) {
            matches_ = other.matches_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMatchesIsMutable();
            matches_.addAll(other.matches_);
          }
          onChanged();
        }
      } else {
        if (!other.matches_.isEmpty()) {
          if (matchesBuilder_.isEmpty()) {
            matchesBuilder_.dispose();
            matchesBuilder_ = null;
            matches_ = other.matches_;
            bitField0_ = (bitField0_ & ~0x00000001);
            matchesBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders
                    ? getMatchesFieldBuilder()
                    : null;
          } else {
            matchesBuilder_.addAllMessages(other.matches_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.cloud.conformance.storage.v1.PolicyConditions parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage =
            (com.google.cloud.conformance.storage.v1.PolicyConditions) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int bitField0_;

    private java.lang.Object successActionStatus_ = "";
    /**
     * <code>string successActionStatus = 1;</code>
     *
     * @return The successActionStatus.
     */
    public java.lang.String getSuccessActionStatus() {
      java.lang.Object ref = successActionStatus_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        successActionStatus_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string successActionStatus = 1;</code>
     *
     * @return The bytes for successActionStatus.
     */
    public com.google.protobuf.ByteString getSuccessActionStatusBytes() {
      java.lang.Object ref = successActionStatus_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        successActionStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string successActionStatus = 1;</code>
     *
     * @param value The successActionStatus to set.
     * @return This builder for chaining.
     */
    public Builder setSuccessActionStatus(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      successActionStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string successActionStatus = 1;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearSuccessActionStatus() {

      successActionStatus_ = getDefaultInstance().getSuccessActionStatus();
      onChanged();
      return this;
    }
    /**
     * <code>string successActionStatus = 1;</code>
     *
     * @param value The bytes for successActionStatus to set.
     * @return This builder for chaining.
     */
    public Builder setSuccessActionStatusBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      successActionStatus_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object successActionRedirect_ = "";
    /**
     * <code>string successActionRedirect = 2;</code>
     *
     * @return The successActionRedirect.
     */
    public java.lang.String getSuccessActionRedirect() {
      java.lang.Object ref = successActionRedirect_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        successActionRedirect_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string successActionRedirect = 2;</code>
     *
     * @return The bytes for successActionRedirect.
     */
    public com.google.protobuf.ByteString getSuccessActionRedirectBytes() {
      java.lang.Object ref = successActionRedirect_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        successActionRedirect_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string successActionRedirect = 2;</code>
     *
     * @param value The successActionRedirect to set.
     * @return This builder for chaining.
     */
    public Builder setSuccessActionRedirect(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      successActionRedirect_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string successActionRedirect = 2;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearSuccessActionRedirect() {

      successActionRedirect_ = getDefaultInstance().getSuccessActionRedirect();
      onChanged();
      return this;
    }
    /**
     * <code>string successActionRedirect = 2;</code>
     *
     * @param value The bytes for successActionRedirect to set.
     * @return This builder for chaining.
     */
    public Builder setSuccessActionRedirectBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      successActionRedirect_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.google.cloud.conformance.storage.v1.ConditionalMatches> matches_ =
        java.util.Collections.emptyList();

    private void ensureMatchesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        matches_ =
            new java.util.ArrayList<com.google.cloud.conformance.storage.v1.ConditionalMatches>(
                matches_);
        bitField0_ |= 0x00000001;
      }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.cloud.conformance.storage.v1.ConditionalMatches,
            com.google.cloud.conformance.storage.v1.ConditionalMatches.Builder,
            com.google.cloud.conformance.storage.v1.ConditionalMatchesOrBuilder>
        matchesBuilder_;

    /**
     * <code>repeated .google.cloud.conformance.storage.v1.ConditionalMatches matches = 3;</code>
     */
    public java.util.List<com.google.cloud.conformance.storage.v1.ConditionalMatches>
        getMatchesList() {
      if (matchesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(matches_);
      } else {
        return matchesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .google.cloud.conformance.storage.v1.ConditionalMatches matches = 3;</code>
     */
    public int getMatchesCount() {
      if (matchesBuilder_ == null) {
        return matches_.size();
      } else {
        return matchesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .google.cloud.conformance.storage.v1.ConditionalMatches matches = 3;</code>
     */
    public com.google.cloud.conformance.storage.v1.ConditionalMatches getMatches(int index) {
      if (matchesBuilder_ == null) {
        return matches_.get(index);
      } else {
        return matchesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .google.cloud.conformance.storage.v1.ConditionalMatches matches = 3;</code>
     */
    public Builder setMatches(
        int index, com.google.cloud.conformance.storage.v1.ConditionalMatches value) {
      if (matchesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMatchesIsMutable();
        matches_.set(index, value);
        onChanged();
      } else {
        matchesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.cloud.conformance.storage.v1.ConditionalMatches matches = 3;</code>
     */
    public Builder setMatches(
        int index,
        com.google.cloud.conformance.storage.v1.ConditionalMatches.Builder builderForValue) {
      if (matchesBuilder_ == null) {
        ensureMatchesIsMutable();
        matches_.set(index, builderForValue.build());
        onChanged();
      } else {
        matchesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.cloud.conformance.storage.v1.ConditionalMatches matches = 3;</code>
     */
    public Builder addMatches(com.google.cloud.conformance.storage.v1.ConditionalMatches value) {
      if (matchesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMatchesIsMutable();
        matches_.add(value);
        onChanged();
      } else {
        matchesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .google.cloud.conformance.storage.v1.ConditionalMatches matches = 3;</code>
     */
    public Builder addMatches(
        int index, com.google.cloud.conformance.storage.v1.ConditionalMatches value) {
      if (matchesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMatchesIsMutable();
        matches_.add(index, value);
        onChanged();
      } else {
        matchesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.cloud.conformance.storage.v1.ConditionalMatches matches = 3;</code>
     */
    public Builder addMatches(
        com.google.cloud.conformance.storage.v1.ConditionalMatches.Builder builderForValue) {
      if (matchesBuilder_ == null) {
        ensureMatchesIsMutable();
        matches_.add(builderForValue.build());
        onChanged();
      } else {
        matchesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.cloud.conformance.storage.v1.ConditionalMatches matches = 3;</code>
     */
    public Builder addMatches(
        int index,
        com.google.cloud.conformance.storage.v1.ConditionalMatches.Builder builderForValue) {
      if (matchesBuilder_ == null) {
        ensureMatchesIsMutable();
        matches_.add(index, builderForValue.build());
        onChanged();
      } else {
        matchesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.cloud.conformance.storage.v1.ConditionalMatches matches = 3;</code>
     */
    public Builder addAllMatches(
        java.lang.Iterable<? extends com.google.cloud.conformance.storage.v1.ConditionalMatches>
            values) {
      if (matchesBuilder_ == null) {
        ensureMatchesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(values, matches_);
        onChanged();
      } else {
        matchesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .google.cloud.conformance.storage.v1.ConditionalMatches matches = 3;</code>
     */
    public Builder clearMatches() {
      if (matchesBuilder_ == null) {
        matches_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        matchesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .google.cloud.conformance.storage.v1.ConditionalMatches matches = 3;</code>
     */
    public Builder removeMatches(int index) {
      if (matchesBuilder_ == null) {
        ensureMatchesIsMutable();
        matches_.remove(index);
        onChanged();
      } else {
        matchesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .google.cloud.conformance.storage.v1.ConditionalMatches matches = 3;</code>
     */
    public com.google.cloud.conformance.storage.v1.ConditionalMatches.Builder getMatchesBuilder(
        int index) {
      return getMatchesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .google.cloud.conformance.storage.v1.ConditionalMatches matches = 3;</code>
     */
    public com.google.cloud.conformance.storage.v1.ConditionalMatchesOrBuilder getMatchesOrBuilder(
        int index) {
      if (matchesBuilder_ == null) {
        return matches_.get(index);
      } else {
        return matchesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .google.cloud.conformance.storage.v1.ConditionalMatches matches = 3;</code>
     */
    public java.util.List<
            ? extends com.google.cloud.conformance.storage.v1.ConditionalMatchesOrBuilder>
        getMatchesOrBuilderList() {
      if (matchesBuilder_ != null) {
        return matchesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(matches_);
      }
    }
    /**
     * <code>repeated .google.cloud.conformance.storage.v1.ConditionalMatches matches = 3;</code>
     */
    public com.google.cloud.conformance.storage.v1.ConditionalMatches.Builder addMatchesBuilder() {
      return getMatchesFieldBuilder()
          .addBuilder(
              com.google.cloud.conformance.storage.v1.ConditionalMatches.getDefaultInstance());
    }
    /**
     * <code>repeated .google.cloud.conformance.storage.v1.ConditionalMatches matches = 3;</code>
     */
    public com.google.cloud.conformance.storage.v1.ConditionalMatches.Builder addMatchesBuilder(
        int index) {
      return getMatchesFieldBuilder()
          .addBuilder(
              index,
              com.google.cloud.conformance.storage.v1.ConditionalMatches.getDefaultInstance());
    }
    /**
     * <code>repeated .google.cloud.conformance.storage.v1.ConditionalMatches matches = 3;</code>
     */
    public java.util.List<com.google.cloud.conformance.storage.v1.ConditionalMatches.Builder>
        getMatchesBuilderList() {
      return getMatchesFieldBuilder().getBuilderList();
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.cloud.conformance.storage.v1.ConditionalMatches,
            com.google.cloud.conformance.storage.v1.ConditionalMatches.Builder,
            com.google.cloud.conformance.storage.v1.ConditionalMatchesOrBuilder>
        getMatchesFieldBuilder() {
      if (matchesBuilder_ == null) {
        matchesBuilder_ =
            new com.google.protobuf.RepeatedFieldBuilderV3<
                com.google.cloud.conformance.storage.v1.ConditionalMatches,
                com.google.cloud.conformance.storage.v1.ConditionalMatches.Builder,
                com.google.cloud.conformance.storage.v1.ConditionalMatchesOrBuilder>(
                matches_, ((bitField0_ & 0x00000001) != 0), getParentForChildren(), isClean());
        matches_ = null;
      }
      return matchesBuilder_;
    }

    @java.lang.Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:google.cloud.conformance.storage.v1.PolicyConditions)
  }

  // @@protoc_insertion_point(class_scope:google.cloud.conformance.storage.v1.PolicyConditions)
  private static final com.google.cloud.conformance.storage.v1.PolicyConditions DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new com.google.cloud.conformance.storage.v1.PolicyConditions();
  }

  public static com.google.cloud.conformance.storage.v1.PolicyConditions getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PolicyConditions> PARSER =
      new com.google.protobuf.AbstractParser<PolicyConditions>() {
        @java.lang.Override
        public PolicyConditions parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new PolicyConditions(input, extensionRegistry);
        }
      };

  public static com.google.protobuf.Parser<PolicyConditions> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PolicyConditions> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.cloud.conformance.storage.v1.PolicyConditions getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
