/*
 * Copyright 2019 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/conformance/storage/v1/tests.proto

// Protobuf Java Version: 3.25.3
package com.google.cloud.conformance.storage.v1;

/**
 *
 *
 * <pre>
 * Test resources that are necessary for a method call. For example,
 * storage.objects.get would require BUCKET and OBJECT.
 * </pre>
 *
 * Protobuf enum {@code google.cloud.conformance.storage.v1.Resource}
 */
public enum Resource implements com.google.protobuf.ProtocolMessageEnum {
  /** <code>BUCKET = 0;</code> */
  BUCKET(0),
  /** <code>OBJECT = 1;</code> */
  OBJECT(1),
  /** <code>NOTIFICATION = 2;</code> */
  NOTIFICATION(2),
  /** <code>HMAC_KEY = 3;</code> */
  HMAC_KEY(3),
  UNRECOGNIZED(-1),
  ;

  /** <code>BUCKET = 0;</code> */
  public static final int BUCKET_VALUE = 0;

  /** <code>OBJECT = 1;</code> */
  public static final int OBJECT_VALUE = 1;

  /** <code>NOTIFICATION = 2;</code> */
  public static final int NOTIFICATION_VALUE = 2;

  /** <code>HMAC_KEY = 3;</code> */
  public static final int HMAC_KEY_VALUE = 3;

  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Resource valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Resource forNumber(int value) {
    switch (value) {
      case 0:
        return BUCKET;
      case 1:
        return OBJECT;
      case 2:
        return NOTIFICATION;
      case 3:
        return HMAC_KEY;
      default:
        return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Resource> internalGetValueMap() {
    return internalValueMap;
  }

  private static final com.google.protobuf.Internal.EnumLiteMap<Resource> internalValueMap =
      new com.google.protobuf.Internal.EnumLiteMap<Resource>() {
        public Resource findValueByNumber(int number) {
          return Resource.forNumber(number);
        }
      };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }

  public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
    return getDescriptor();
  }

  public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
    return com.google.cloud.conformance.storage.v1.Tests.getDescriptor().getEnumTypes().get(1);
  }

  private static final Resource[] VALUES = values();

  public static Resource valueOf(com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException("EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Resource(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:google.cloud.conformance.storage.v1.Resource)
}
