/*
 * Copyright 2019 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/conformance/storage/v1/tests.proto

package com.google.cloud.conformance.storage.v1;

/**
 *
 *
 * <pre>
 * Schema for a retry test, corresponding to a single scenario from the design
 * doc.
 * </pre>
 *
 * Protobuf type {@code google.cloud.conformance.storage.v1.RetryTest}
 */
public final class RetryTest extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:google.cloud.conformance.storage.v1.RetryTest)
    RetryTestOrBuilder {
  private static final long serialVersionUID = 0L;
  // Use RetryTest.newBuilder() to construct.
  private RetryTest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private RetryTest() {
    description_ = "";
    cases_ = java.util.Collections.emptyList();
    methods_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
    return new RetryTest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
    return this.unknownFields;
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return com.google.cloud.conformance.storage.v1.Tests
        .internal_static_google_cloud_conformance_storage_v1_RetryTest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.cloud.conformance.storage.v1.Tests
        .internal_static_google_cloud_conformance_storage_v1_RetryTest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.cloud.conformance.storage.v1.RetryTest.class,
            com.google.cloud.conformance.storage.v1.RetryTest.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_ = 0;
  /**
   *
   *
   * <pre>
   * Scenario number
   * </pre>
   *
   * <code>int32 id = 1;</code>
   *
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 2;

  @SuppressWarnings("serial")
  private volatile java.lang.Object description_ = "";
  /**
   *
   *
   * <pre>
   * Human-readable description of the test case.
   * </pre>
   *
   * <code>string description = 2;</code>
   *
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   *
   *
   * <pre>
   * Human-readable description of the test case.
   * </pre>
   *
   * <code>string description = 2;</code>
   *
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CASES_FIELD_NUMBER = 3;

  @SuppressWarnings("serial")
  private java.util.List<com.google.cloud.conformance.storage.v1.InstructionList> cases_;
  /**
   *
   *
   * <pre>
   * list of emulator instruction sets.
   * </pre>
   *
   * <code>repeated .google.cloud.conformance.storage.v1.InstructionList cases = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.google.cloud.conformance.storage.v1.InstructionList> getCasesList() {
    return cases_;
  }
  /**
   *
   *
   * <pre>
   * list of emulator instruction sets.
   * </pre>
   *
   * <code>repeated .google.cloud.conformance.storage.v1.InstructionList cases = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.cloud.conformance.storage.v1.InstructionListOrBuilder>
      getCasesOrBuilderList() {
    return cases_;
  }
  /**
   *
   *
   * <pre>
   * list of emulator instruction sets.
   * </pre>
   *
   * <code>repeated .google.cloud.conformance.storage.v1.InstructionList cases = 3;</code>
   */
  @java.lang.Override
  public int getCasesCount() {
    return cases_.size();
  }
  /**
   *
   *
   * <pre>
   * list of emulator instruction sets.
   * </pre>
   *
   * <code>repeated .google.cloud.conformance.storage.v1.InstructionList cases = 3;</code>
   */
  @java.lang.Override
  public com.google.cloud.conformance.storage.v1.InstructionList getCases(int index) {
    return cases_.get(index);
  }
  /**
   *
   *
   * <pre>
   * list of emulator instruction sets.
   * </pre>
   *
   * <code>repeated .google.cloud.conformance.storage.v1.InstructionList cases = 3;</code>
   */
  @java.lang.Override
  public com.google.cloud.conformance.storage.v1.InstructionListOrBuilder getCasesOrBuilder(
      int index) {
    return cases_.get(index);
  }

  public static final int METHODS_FIELD_NUMBER = 4;

  @SuppressWarnings("serial")
  private java.util.List<com.google.cloud.conformance.storage.v1.Method> methods_;
  /**
   *
   *
   * <pre>
   * List of API methods to be tested.
   * </pre>
   *
   * <code>repeated .google.cloud.conformance.storage.v1.Method methods = 4;</code>
   */
  @java.lang.Override
  public java.util.List<com.google.cloud.conformance.storage.v1.Method> getMethodsList() {
    return methods_;
  }
  /**
   *
   *
   * <pre>
   * List of API methods to be tested.
   * </pre>
   *
   * <code>repeated .google.cloud.conformance.storage.v1.Method methods = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.cloud.conformance.storage.v1.MethodOrBuilder>
      getMethodsOrBuilderList() {
    return methods_;
  }
  /**
   *
   *
   * <pre>
   * List of API methods to be tested.
   * </pre>
   *
   * <code>repeated .google.cloud.conformance.storage.v1.Method methods = 4;</code>
   */
  @java.lang.Override
  public int getMethodsCount() {
    return methods_.size();
  }
  /**
   *
   *
   * <pre>
   * List of API methods to be tested.
   * </pre>
   *
   * <code>repeated .google.cloud.conformance.storage.v1.Method methods = 4;</code>
   */
  @java.lang.Override
  public com.google.cloud.conformance.storage.v1.Method getMethods(int index) {
    return methods_.get(index);
  }
  /**
   *
   *
   * <pre>
   * List of API methods to be tested.
   * </pre>
   *
   * <code>repeated .google.cloud.conformance.storage.v1.Method methods = 4;</code>
   */
  @java.lang.Override
  public com.google.cloud.conformance.storage.v1.MethodOrBuilder getMethodsOrBuilder(int index) {
    return methods_.get(index);
  }

  public static final int PRECONDITIONPROVIDED_FIELD_NUMBER = 5;
  private boolean preconditionProvided_ = false;
  /**
   *
   *
   * <pre>
   * Whether a precondition is provided (for conditionally-idempotent methods
   * only).
   * </pre>
   *
   * <code>bool preconditionProvided = 5;</code>
   *
   * @return The preconditionProvided.
   */
  @java.lang.Override
  public boolean getPreconditionProvided() {
    return preconditionProvided_;
  }

  public static final int EXPECTSUCCESS_FIELD_NUMBER = 6;
  private boolean expectSuccess_ = false;
  /**
   *
   *
   * <pre>
   * Whether we expect the method calls to eventually succeed after the client
   * library retries.
   * </pre>
   *
   * <code>bool expectSuccess = 6;</code>
   *
   * @return The expectSuccess.
   */
  @java.lang.Override
  public boolean getExpectSuccess() {
    return expectSuccess_;
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, description_);
    }
    for (int i = 0; i < cases_.size(); i++) {
      output.writeMessage(3, cases_.get(i));
    }
    for (int i = 0; i < methods_.size(); i++) {
      output.writeMessage(4, methods_.get(i));
    }
    if (preconditionProvided_ != false) {
      output.writeBool(5, preconditionProvided_);
    }
    if (expectSuccess_ != false) {
      output.writeBool(6, expectSuccess_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream.computeInt32Size(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, description_);
    }
    for (int i = 0; i < cases_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(3, cases_.get(i));
    }
    for (int i = 0; i < methods_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(4, methods_.get(i));
    }
    if (preconditionProvided_ != false) {
      size += com.google.protobuf.CodedOutputStream.computeBoolSize(5, preconditionProvided_);
    }
    if (expectSuccess_ != false) {
      size += com.google.protobuf.CodedOutputStream.computeBoolSize(6, expectSuccess_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof com.google.cloud.conformance.storage.v1.RetryTest)) {
      return super.equals(obj);
    }
    com.google.cloud.conformance.storage.v1.RetryTest other =
        (com.google.cloud.conformance.storage.v1.RetryTest) obj;

    if (getId() != other.getId()) return false;
    if (!getDescription().equals(other.getDescription())) return false;
    if (!getCasesList().equals(other.getCasesList())) return false;
    if (!getMethodsList().equals(other.getMethodsList())) return false;
    if (getPreconditionProvided() != other.getPreconditionProvided()) return false;
    if (getExpectSuccess() != other.getExpectSuccess()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    if (getCasesCount() > 0) {
      hash = (37 * hash) + CASES_FIELD_NUMBER;
      hash = (53 * hash) + getCasesList().hashCode();
    }
    if (getMethodsCount() > 0) {
      hash = (37 * hash) + METHODS_FIELD_NUMBER;
      hash = (53 * hash) + getMethodsList().hashCode();
    }
    hash = (37 * hash) + PRECONDITIONPROVIDED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(getPreconditionProvided());
    hash = (37 * hash) + EXPECTSUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(getExpectSuccess());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.cloud.conformance.storage.v1.RetryTest parseFrom(
      java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.cloud.conformance.storage.v1.RetryTest parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.cloud.conformance.storage.v1.RetryTest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.cloud.conformance.storage.v1.RetryTest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.cloud.conformance.storage.v1.RetryTest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.cloud.conformance.storage.v1.RetryTest parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.cloud.conformance.storage.v1.RetryTest parseFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.google.cloud.conformance.storage.v1.RetryTest parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.google.cloud.conformance.storage.v1.RetryTest parseDelimitedFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.cloud.conformance.storage.v1.RetryTest parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.google.cloud.conformance.storage.v1.RetryTest parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.google.cloud.conformance.storage.v1.RetryTest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(com.google.cloud.conformance.storage.v1.RetryTest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   *
   *
   * <pre>
   * Schema for a retry test, corresponding to a single scenario from the design
   * doc.
   * </pre>
   *
   * Protobuf type {@code google.cloud.conformance.storage.v1.RetryTest}
   */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:google.cloud.conformance.storage.v1.RetryTest)
      com.google.cloud.conformance.storage.v1.RetryTestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.google.cloud.conformance.storage.v1.Tests
          .internal_static_google_cloud_conformance_storage_v1_RetryTest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.cloud.conformance.storage.v1.Tests
          .internal_static_google_cloud_conformance_storage_v1_RetryTest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.cloud.conformance.storage.v1.RetryTest.class,
              com.google.cloud.conformance.storage.v1.RetryTest.Builder.class);
    }

    // Construct using com.google.cloud.conformance.storage.v1.RetryTest.newBuilder()
    private Builder() {}

    private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0;
      description_ = "";
      if (casesBuilder_ == null) {
        cases_ = java.util.Collections.emptyList();
      } else {
        cases_ = null;
        casesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      if (methodsBuilder_ == null) {
        methods_ = java.util.Collections.emptyList();
      } else {
        methods_ = null;
        methodsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      preconditionProvided_ = false;
      expectSuccess_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return com.google.cloud.conformance.storage.v1.Tests
          .internal_static_google_cloud_conformance_storage_v1_RetryTest_descriptor;
    }

    @java.lang.Override
    public com.google.cloud.conformance.storage.v1.RetryTest getDefaultInstanceForType() {
      return com.google.cloud.conformance.storage.v1.RetryTest.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.cloud.conformance.storage.v1.RetryTest build() {
      com.google.cloud.conformance.storage.v1.RetryTest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.cloud.conformance.storage.v1.RetryTest buildPartial() {
      com.google.cloud.conformance.storage.v1.RetryTest result =
          new com.google.cloud.conformance.storage.v1.RetryTest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) {
        buildPartial0(result);
      }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(
        com.google.cloud.conformance.storage.v1.RetryTest result) {
      if (casesBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          cases_ = java.util.Collections.unmodifiableList(cases_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.cases_ = cases_;
      } else {
        result.cases_ = casesBuilder_.build();
      }
      if (methodsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          methods_ = java.util.Collections.unmodifiableList(methods_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.methods_ = methods_;
      } else {
        result.methods_ = methodsBuilder_.build();
      }
    }

    private void buildPartial0(com.google.cloud.conformance.storage.v1.RetryTest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.description_ = description_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.preconditionProvided_ = preconditionProvided_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.expectSuccess_ = expectSuccess_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.cloud.conformance.storage.v1.RetryTest) {
        return mergeFrom((com.google.cloud.conformance.storage.v1.RetryTest) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.cloud.conformance.storage.v1.RetryTest other) {
      if (other == com.google.cloud.conformance.storage.v1.RetryTest.getDefaultInstance())
        return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (casesBuilder_ == null) {
        if (!other.cases_.isEmpty()) {
          if (cases_.isEmpty()) {
            cases_ = other.cases_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureCasesIsMutable();
            cases_.addAll(other.cases_);
          }
          onChanged();
        }
      } else {
        if (!other.cases_.isEmpty()) {
          if (casesBuilder_.isEmpty()) {
            casesBuilder_.dispose();
            casesBuilder_ = null;
            cases_ = other.cases_;
            bitField0_ = (bitField0_ & ~0x00000004);
            casesBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders
                    ? getCasesFieldBuilder()
                    : null;
          } else {
            casesBuilder_.addAllMessages(other.cases_);
          }
        }
      }
      if (methodsBuilder_ == null) {
        if (!other.methods_.isEmpty()) {
          if (methods_.isEmpty()) {
            methods_ = other.methods_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureMethodsIsMutable();
            methods_.addAll(other.methods_);
          }
          onChanged();
        }
      } else {
        if (!other.methods_.isEmpty()) {
          if (methodsBuilder_.isEmpty()) {
            methodsBuilder_.dispose();
            methodsBuilder_ = null;
            methods_ = other.methods_;
            bitField0_ = (bitField0_ & ~0x00000008);
            methodsBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders
                    ? getMethodsFieldBuilder()
                    : null;
          } else {
            methodsBuilder_.addAllMessages(other.methods_);
          }
        }
      }
      if (other.getPreconditionProvided() != false) {
        setPreconditionProvided(other.getPreconditionProvided());
      }
      if (other.getExpectSuccess() != false) {
        setExpectSuccess(other.getExpectSuccess());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8:
              {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
            case 18:
              {
                description_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
            case 26:
              {
                com.google.cloud.conformance.storage.v1.InstructionList m =
                    input.readMessage(
                        com.google.cloud.conformance.storage.v1.InstructionList.parser(),
                        extensionRegistry);
                if (casesBuilder_ == null) {
                  ensureCasesIsMutable();
                  cases_.add(m);
                } else {
                  casesBuilder_.addMessage(m);
                }
                break;
              } // case 26
            case 34:
              {
                com.google.cloud.conformance.storage.v1.Method m =
                    input.readMessage(
                        com.google.cloud.conformance.storage.v1.Method.parser(), extensionRegistry);
                if (methodsBuilder_ == null) {
                  ensureMethodsIsMutable();
                  methods_.add(m);
                } else {
                  methodsBuilder_.addMessage(m);
                }
                break;
              } // case 34
            case 40:
              {
                preconditionProvided_ = input.readBool();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
            case 48:
              {
                expectSuccess_ = input.readBool();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
            default:
              {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private int bitField0_;

    private int id_;
    /**
     *
     *
     * <pre>
     * Scenario number
     * </pre>
     *
     * <code>int32 id = 1;</code>
     *
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     *
     *
     * <pre>
     * Scenario number
     * </pre>
     *
     * <code>int32 id = 1;</code>
     *
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {

      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Scenario number
     * </pre>
     *
     * <code>int32 id = 1;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     *
     *
     * <pre>
     * Human-readable description of the test case.
     * </pre>
     *
     * <code>string description = 2;</code>
     *
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * Human-readable description of the test case.
     * </pre>
     *
     * <code>string description = 2;</code>
     *
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * Human-readable description of the test case.
     * </pre>
     *
     * <code>string description = 2;</code>
     *
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      description_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Human-readable description of the test case.
     * </pre>
     *
     * <code>string description = 2;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      description_ = getDefaultInstance().getDescription();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Human-readable description of the test case.
     * </pre>
     *
     * <code>string description = 2;</code>
     *
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      description_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.util.List<com.google.cloud.conformance.storage.v1.InstructionList> cases_ =
        java.util.Collections.emptyList();

    private void ensureCasesIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        cases_ =
            new java.util.ArrayList<com.google.cloud.conformance.storage.v1.InstructionList>(
                cases_);
        bitField0_ |= 0x00000004;
      }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.cloud.conformance.storage.v1.InstructionList,
            com.google.cloud.conformance.storage.v1.InstructionList.Builder,
            com.google.cloud.conformance.storage.v1.InstructionListOrBuilder>
        casesBuilder_;

    /**
     *
     *
     * <pre>
     * list of emulator instruction sets.
     * </pre>
     *
     * <code>repeated .google.cloud.conformance.storage.v1.InstructionList cases = 3;</code>
     */
    public java.util.List<com.google.cloud.conformance.storage.v1.InstructionList> getCasesList() {
      if (casesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(cases_);
      } else {
        return casesBuilder_.getMessageList();
      }
    }
    /**
     *
     *
     * <pre>
     * list of emulator instruction sets.
     * </pre>
     *
     * <code>repeated .google.cloud.conformance.storage.v1.InstructionList cases = 3;</code>
     */
    public int getCasesCount() {
      if (casesBuilder_ == null) {
        return cases_.size();
      } else {
        return casesBuilder_.getCount();
      }
    }
    /**
     *
     *
     * <pre>
     * list of emulator instruction sets.
     * </pre>
     *
     * <code>repeated .google.cloud.conformance.storage.v1.InstructionList cases = 3;</code>
     */
    public com.google.cloud.conformance.storage.v1.InstructionList getCases(int index) {
      if (casesBuilder_ == null) {
        return cases_.get(index);
      } else {
        return casesBuilder_.getMessage(index);
      }
    }
    /**
     *
     *
     * <pre>
     * list of emulator instruction sets.
     * </pre>
     *
     * <code>repeated .google.cloud.conformance.storage.v1.InstructionList cases = 3;</code>
     */
    public Builder setCases(
        int index, com.google.cloud.conformance.storage.v1.InstructionList value) {
      if (casesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCasesIsMutable();
        cases_.set(index, value);
        onChanged();
      } else {
        casesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     *
     *
     * <pre>
     * list of emulator instruction sets.
     * </pre>
     *
     * <code>repeated .google.cloud.conformance.storage.v1.InstructionList cases = 3;</code>
     */
    public Builder setCases(
        int index,
        com.google.cloud.conformance.storage.v1.InstructionList.Builder builderForValue) {
      if (casesBuilder_ == null) {
        ensureCasesIsMutable();
        cases_.set(index, builderForValue.build());
        onChanged();
      } else {
        casesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     *
     *
     * <pre>
     * list of emulator instruction sets.
     * </pre>
     *
     * <code>repeated .google.cloud.conformance.storage.v1.InstructionList cases = 3;</code>
     */
    public Builder addCases(com.google.cloud.conformance.storage.v1.InstructionList value) {
      if (casesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCasesIsMutable();
        cases_.add(value);
        onChanged();
      } else {
        casesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     *
     *
     * <pre>
     * list of emulator instruction sets.
     * </pre>
     *
     * <code>repeated .google.cloud.conformance.storage.v1.InstructionList cases = 3;</code>
     */
    public Builder addCases(
        int index, com.google.cloud.conformance.storage.v1.InstructionList value) {
      if (casesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCasesIsMutable();
        cases_.add(index, value);
        onChanged();
      } else {
        casesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     *
     *
     * <pre>
     * list of emulator instruction sets.
     * </pre>
     *
     * <code>repeated .google.cloud.conformance.storage.v1.InstructionList cases = 3;</code>
     */
    public Builder addCases(
        com.google.cloud.conformance.storage.v1.InstructionList.Builder builderForValue) {
      if (casesBuilder_ == null) {
        ensureCasesIsMutable();
        cases_.add(builderForValue.build());
        onChanged();
      } else {
        casesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     *
     *
     * <pre>
     * list of emulator instruction sets.
     * </pre>
     *
     * <code>repeated .google.cloud.conformance.storage.v1.InstructionList cases = 3;</code>
     */
    public Builder addCases(
        int index,
        com.google.cloud.conformance.storage.v1.InstructionList.Builder builderForValue) {
      if (casesBuilder_ == null) {
        ensureCasesIsMutable();
        cases_.add(index, builderForValue.build());
        onChanged();
      } else {
        casesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     *
     *
     * <pre>
     * list of emulator instruction sets.
     * </pre>
     *
     * <code>repeated .google.cloud.conformance.storage.v1.InstructionList cases = 3;</code>
     */
    public Builder addAllCases(
        java.lang.Iterable<? extends com.google.cloud.conformance.storage.v1.InstructionList>
            values) {
      if (casesBuilder_ == null) {
        ensureCasesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(values, cases_);
        onChanged();
      } else {
        casesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     *
     *
     * <pre>
     * list of emulator instruction sets.
     * </pre>
     *
     * <code>repeated .google.cloud.conformance.storage.v1.InstructionList cases = 3;</code>
     */
    public Builder clearCases() {
      if (casesBuilder_ == null) {
        cases_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        casesBuilder_.clear();
      }
      return this;
    }
    /**
     *
     *
     * <pre>
     * list of emulator instruction sets.
     * </pre>
     *
     * <code>repeated .google.cloud.conformance.storage.v1.InstructionList cases = 3;</code>
     */
    public Builder removeCases(int index) {
      if (casesBuilder_ == null) {
        ensureCasesIsMutable();
        cases_.remove(index);
        onChanged();
      } else {
        casesBuilder_.remove(index);
      }
      return this;
    }
    /**
     *
     *
     * <pre>
     * list of emulator instruction sets.
     * </pre>
     *
     * <code>repeated .google.cloud.conformance.storage.v1.InstructionList cases = 3;</code>
     */
    public com.google.cloud.conformance.storage.v1.InstructionList.Builder getCasesBuilder(
        int index) {
      return getCasesFieldBuilder().getBuilder(index);
    }
    /**
     *
     *
     * <pre>
     * list of emulator instruction sets.
     * </pre>
     *
     * <code>repeated .google.cloud.conformance.storage.v1.InstructionList cases = 3;</code>
     */
    public com.google.cloud.conformance.storage.v1.InstructionListOrBuilder getCasesOrBuilder(
        int index) {
      if (casesBuilder_ == null) {
        return cases_.get(index);
      } else {
        return casesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     *
     *
     * <pre>
     * list of emulator instruction sets.
     * </pre>
     *
     * <code>repeated .google.cloud.conformance.storage.v1.InstructionList cases = 3;</code>
     */
    public java.util.List<
            ? extends com.google.cloud.conformance.storage.v1.InstructionListOrBuilder>
        getCasesOrBuilderList() {
      if (casesBuilder_ != null) {
        return casesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(cases_);
      }
    }
    /**
     *
     *
     * <pre>
     * list of emulator instruction sets.
     * </pre>
     *
     * <code>repeated .google.cloud.conformance.storage.v1.InstructionList cases = 3;</code>
     */
    public com.google.cloud.conformance.storage.v1.InstructionList.Builder addCasesBuilder() {
      return getCasesFieldBuilder()
          .addBuilder(com.google.cloud.conformance.storage.v1.InstructionList.getDefaultInstance());
    }
    /**
     *
     *
     * <pre>
     * list of emulator instruction sets.
     * </pre>
     *
     * <code>repeated .google.cloud.conformance.storage.v1.InstructionList cases = 3;</code>
     */
    public com.google.cloud.conformance.storage.v1.InstructionList.Builder addCasesBuilder(
        int index) {
      return getCasesFieldBuilder()
          .addBuilder(
              index, com.google.cloud.conformance.storage.v1.InstructionList.getDefaultInstance());
    }
    /**
     *
     *
     * <pre>
     * list of emulator instruction sets.
     * </pre>
     *
     * <code>repeated .google.cloud.conformance.storage.v1.InstructionList cases = 3;</code>
     */
    public java.util.List<com.google.cloud.conformance.storage.v1.InstructionList.Builder>
        getCasesBuilderList() {
      return getCasesFieldBuilder().getBuilderList();
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.cloud.conformance.storage.v1.InstructionList,
            com.google.cloud.conformance.storage.v1.InstructionList.Builder,
            com.google.cloud.conformance.storage.v1.InstructionListOrBuilder>
        getCasesFieldBuilder() {
      if (casesBuilder_ == null) {
        casesBuilder_ =
            new com.google.protobuf.RepeatedFieldBuilderV3<
                com.google.cloud.conformance.storage.v1.InstructionList,
                com.google.cloud.conformance.storage.v1.InstructionList.Builder,
                com.google.cloud.conformance.storage.v1.InstructionListOrBuilder>(
                cases_, ((bitField0_ & 0x00000004) != 0), getParentForChildren(), isClean());
        cases_ = null;
      }
      return casesBuilder_;
    }

    private java.util.List<com.google.cloud.conformance.storage.v1.Method> methods_ =
        java.util.Collections.emptyList();

    private void ensureMethodsIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        methods_ =
            new java.util.ArrayList<com.google.cloud.conformance.storage.v1.Method>(methods_);
        bitField0_ |= 0x00000008;
      }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.cloud.conformance.storage.v1.Method,
            com.google.cloud.conformance.storage.v1.Method.Builder,
            com.google.cloud.conformance.storage.v1.MethodOrBuilder>
        methodsBuilder_;

    /**
     *
     *
     * <pre>
     * List of API methods to be tested.
     * </pre>
     *
     * <code>repeated .google.cloud.conformance.storage.v1.Method methods = 4;</code>
     */
    public java.util.List<com.google.cloud.conformance.storage.v1.Method> getMethodsList() {
      if (methodsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(methods_);
      } else {
        return methodsBuilder_.getMessageList();
      }
    }
    /**
     *
     *
     * <pre>
     * List of API methods to be tested.
     * </pre>
     *
     * <code>repeated .google.cloud.conformance.storage.v1.Method methods = 4;</code>
     */
    public int getMethodsCount() {
      if (methodsBuilder_ == null) {
        return methods_.size();
      } else {
        return methodsBuilder_.getCount();
      }
    }
    /**
     *
     *
     * <pre>
     * List of API methods to be tested.
     * </pre>
     *
     * <code>repeated .google.cloud.conformance.storage.v1.Method methods = 4;</code>
     */
    public com.google.cloud.conformance.storage.v1.Method getMethods(int index) {
      if (methodsBuilder_ == null) {
        return methods_.get(index);
      } else {
        return methodsBuilder_.getMessage(index);
      }
    }
    /**
     *
     *
     * <pre>
     * List of API methods to be tested.
     * </pre>
     *
     * <code>repeated .google.cloud.conformance.storage.v1.Method methods = 4;</code>
     */
    public Builder setMethods(int index, com.google.cloud.conformance.storage.v1.Method value) {
      if (methodsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMethodsIsMutable();
        methods_.set(index, value);
        onChanged();
      } else {
        methodsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     *
     *
     * <pre>
     * List of API methods to be tested.
     * </pre>
     *
     * <code>repeated .google.cloud.conformance.storage.v1.Method methods = 4;</code>
     */
    public Builder setMethods(
        int index, com.google.cloud.conformance.storage.v1.Method.Builder builderForValue) {
      if (methodsBuilder_ == null) {
        ensureMethodsIsMutable();
        methods_.set(index, builderForValue.build());
        onChanged();
      } else {
        methodsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     *
     *
     * <pre>
     * List of API methods to be tested.
     * </pre>
     *
     * <code>repeated .google.cloud.conformance.storage.v1.Method methods = 4;</code>
     */
    public Builder addMethods(com.google.cloud.conformance.storage.v1.Method value) {
      if (methodsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMethodsIsMutable();
        methods_.add(value);
        onChanged();
      } else {
        methodsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     *
     *
     * <pre>
     * List of API methods to be tested.
     * </pre>
     *
     * <code>repeated .google.cloud.conformance.storage.v1.Method methods = 4;</code>
     */
    public Builder addMethods(int index, com.google.cloud.conformance.storage.v1.Method value) {
      if (methodsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMethodsIsMutable();
        methods_.add(index, value);
        onChanged();
      } else {
        methodsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     *
     *
     * <pre>
     * List of API methods to be tested.
     * </pre>
     *
     * <code>repeated .google.cloud.conformance.storage.v1.Method methods = 4;</code>
     */
    public Builder addMethods(
        com.google.cloud.conformance.storage.v1.Method.Builder builderForValue) {
      if (methodsBuilder_ == null) {
        ensureMethodsIsMutable();
        methods_.add(builderForValue.build());
        onChanged();
      } else {
        methodsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     *
     *
     * <pre>
     * List of API methods to be tested.
     * </pre>
     *
     * <code>repeated .google.cloud.conformance.storage.v1.Method methods = 4;</code>
     */
    public Builder addMethods(
        int index, com.google.cloud.conformance.storage.v1.Method.Builder builderForValue) {
      if (methodsBuilder_ == null) {
        ensureMethodsIsMutable();
        methods_.add(index, builderForValue.build());
        onChanged();
      } else {
        methodsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     *
     *
     * <pre>
     * List of API methods to be tested.
     * </pre>
     *
     * <code>repeated .google.cloud.conformance.storage.v1.Method methods = 4;</code>
     */
    public Builder addAllMethods(
        java.lang.Iterable<? extends com.google.cloud.conformance.storage.v1.Method> values) {
      if (methodsBuilder_ == null) {
        ensureMethodsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(values, methods_);
        onChanged();
      } else {
        methodsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     *
     *
     * <pre>
     * List of API methods to be tested.
     * </pre>
     *
     * <code>repeated .google.cloud.conformance.storage.v1.Method methods = 4;</code>
     */
    public Builder clearMethods() {
      if (methodsBuilder_ == null) {
        methods_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        methodsBuilder_.clear();
      }
      return this;
    }
    /**
     *
     *
     * <pre>
     * List of API methods to be tested.
     * </pre>
     *
     * <code>repeated .google.cloud.conformance.storage.v1.Method methods = 4;</code>
     */
    public Builder removeMethods(int index) {
      if (methodsBuilder_ == null) {
        ensureMethodsIsMutable();
        methods_.remove(index);
        onChanged();
      } else {
        methodsBuilder_.remove(index);
      }
      return this;
    }
    /**
     *
     *
     * <pre>
     * List of API methods to be tested.
     * </pre>
     *
     * <code>repeated .google.cloud.conformance.storage.v1.Method methods = 4;</code>
     */
    public com.google.cloud.conformance.storage.v1.Method.Builder getMethodsBuilder(int index) {
      return getMethodsFieldBuilder().getBuilder(index);
    }
    /**
     *
     *
     * <pre>
     * List of API methods to be tested.
     * </pre>
     *
     * <code>repeated .google.cloud.conformance.storage.v1.Method methods = 4;</code>
     */
    public com.google.cloud.conformance.storage.v1.MethodOrBuilder getMethodsOrBuilder(int index) {
      if (methodsBuilder_ == null) {
        return methods_.get(index);
      } else {
        return methodsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     *
     *
     * <pre>
     * List of API methods to be tested.
     * </pre>
     *
     * <code>repeated .google.cloud.conformance.storage.v1.Method methods = 4;</code>
     */
    public java.util.List<? extends com.google.cloud.conformance.storage.v1.MethodOrBuilder>
        getMethodsOrBuilderList() {
      if (methodsBuilder_ != null) {
        return methodsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(methods_);
      }
    }
    /**
     *
     *
     * <pre>
     * List of API methods to be tested.
     * </pre>
     *
     * <code>repeated .google.cloud.conformance.storage.v1.Method methods = 4;</code>
     */
    public com.google.cloud.conformance.storage.v1.Method.Builder addMethodsBuilder() {
      return getMethodsFieldBuilder()
          .addBuilder(com.google.cloud.conformance.storage.v1.Method.getDefaultInstance());
    }
    /**
     *
     *
     * <pre>
     * List of API methods to be tested.
     * </pre>
     *
     * <code>repeated .google.cloud.conformance.storage.v1.Method methods = 4;</code>
     */
    public com.google.cloud.conformance.storage.v1.Method.Builder addMethodsBuilder(int index) {
      return getMethodsFieldBuilder()
          .addBuilder(index, com.google.cloud.conformance.storage.v1.Method.getDefaultInstance());
    }
    /**
     *
     *
     * <pre>
     * List of API methods to be tested.
     * </pre>
     *
     * <code>repeated .google.cloud.conformance.storage.v1.Method methods = 4;</code>
     */
    public java.util.List<com.google.cloud.conformance.storage.v1.Method.Builder>
        getMethodsBuilderList() {
      return getMethodsFieldBuilder().getBuilderList();
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.cloud.conformance.storage.v1.Method,
            com.google.cloud.conformance.storage.v1.Method.Builder,
            com.google.cloud.conformance.storage.v1.MethodOrBuilder>
        getMethodsFieldBuilder() {
      if (methodsBuilder_ == null) {
        methodsBuilder_ =
            new com.google.protobuf.RepeatedFieldBuilderV3<
                com.google.cloud.conformance.storage.v1.Method,
                com.google.cloud.conformance.storage.v1.Method.Builder,
                com.google.cloud.conformance.storage.v1.MethodOrBuilder>(
                methods_, ((bitField0_ & 0x00000008) != 0), getParentForChildren(), isClean());
        methods_ = null;
      }
      return methodsBuilder_;
    }

    private boolean preconditionProvided_;
    /**
     *
     *
     * <pre>
     * Whether a precondition is provided (for conditionally-idempotent methods
     * only).
     * </pre>
     *
     * <code>bool preconditionProvided = 5;</code>
     *
     * @return The preconditionProvided.
     */
    @java.lang.Override
    public boolean getPreconditionProvided() {
      return preconditionProvided_;
    }
    /**
     *
     *
     * <pre>
     * Whether a precondition is provided (for conditionally-idempotent methods
     * only).
     * </pre>
     *
     * <code>bool preconditionProvided = 5;</code>
     *
     * @param value The preconditionProvided to set.
     * @return This builder for chaining.
     */
    public Builder setPreconditionProvided(boolean value) {

      preconditionProvided_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Whether a precondition is provided (for conditionally-idempotent methods
     * only).
     * </pre>
     *
     * <code>bool preconditionProvided = 5;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearPreconditionProvided() {
      bitField0_ = (bitField0_ & ~0x00000010);
      preconditionProvided_ = false;
      onChanged();
      return this;
    }

    private boolean expectSuccess_;
    /**
     *
     *
     * <pre>
     * Whether we expect the method calls to eventually succeed after the client
     * library retries.
     * </pre>
     *
     * <code>bool expectSuccess = 6;</code>
     *
     * @return The expectSuccess.
     */
    @java.lang.Override
    public boolean getExpectSuccess() {
      return expectSuccess_;
    }
    /**
     *
     *
     * <pre>
     * Whether we expect the method calls to eventually succeed after the client
     * library retries.
     * </pre>
     *
     * <code>bool expectSuccess = 6;</code>
     *
     * @param value The expectSuccess to set.
     * @return This builder for chaining.
     */
    public Builder setExpectSuccess(boolean value) {

      expectSuccess_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Whether we expect the method calls to eventually succeed after the client
     * library retries.
     * </pre>
     *
     * <code>bool expectSuccess = 6;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearExpectSuccess() {
      bitField0_ = (bitField0_ & ~0x00000020);
      expectSuccess_ = false;
      onChanged();
      return this;
    }

    @java.lang.Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:google.cloud.conformance.storage.v1.RetryTest)
  }

  // @@protoc_insertion_point(class_scope:google.cloud.conformance.storage.v1.RetryTest)
  private static final com.google.cloud.conformance.storage.v1.RetryTest DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new com.google.cloud.conformance.storage.v1.RetryTest();
  }

  public static com.google.cloud.conformance.storage.v1.RetryTest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RetryTest> PARSER =
      new com.google.protobuf.AbstractParser<RetryTest>() {
        @java.lang.Override
        public RetryTest parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

  public static com.google.protobuf.Parser<RetryTest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RetryTest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.cloud.conformance.storage.v1.RetryTest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
