/*
 * Copyright 2019 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/conformance/storage/v1/tests.proto

package com.google.cloud.conformance.storage.v1;

/** Protobuf type {@code google.cloud.conformance.storage.v1.SigningV4Test} */
public final class SigningV4Test extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:google.cloud.conformance.storage.v1.SigningV4Test)
    SigningV4TestOrBuilder {
  private static final long serialVersionUID = 0L;
  // Use SigningV4Test.newBuilder() to construct.
  private SigningV4Test(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private SigningV4Test() {
    fileName_ = "";
    description_ = "";
    bucket_ = "";
    object_ = "";
    method_ = "";
    expectedUrl_ = "";
    scheme_ = "";
    urlStyle_ = 0;
    bucketBoundHostname_ = "";
    expectedCanonicalRequest_ = "";
    expectedStringToSign_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
    return new SigningV4Test();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
    return this.unknownFields;
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return com.google.cloud.conformance.storage.v1.Tests
        .internal_static_google_cloud_conformance_storage_v1_SigningV4Test_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(int number) {
    switch (number) {
      case 9:
        return internalGetHeaders();
      case 10:
        return internalGetQueryParameters();
      default:
        throw new RuntimeException("Invalid map field number: " + number);
    }
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.cloud.conformance.storage.v1.Tests
        .internal_static_google_cloud_conformance_storage_v1_SigningV4Test_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.cloud.conformance.storage.v1.SigningV4Test.class,
            com.google.cloud.conformance.storage.v1.SigningV4Test.Builder.class);
  }

  public static final int FILENAME_FIELD_NUMBER = 1;

  @SuppressWarnings("serial")
  private volatile java.lang.Object fileName_ = "";
  /**
   * <code>string fileName = 1;</code>
   *
   * @return The fileName.
   */
  @java.lang.Override
  public java.lang.String getFileName() {
    java.lang.Object ref = fileName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fileName_ = s;
      return s;
    }
  }
  /**
   * <code>string fileName = 1;</code>
   *
   * @return The bytes for fileName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getFileNameBytes() {
    java.lang.Object ref = fileName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      fileName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 2;

  @SuppressWarnings("serial")
  private volatile java.lang.Object description_ = "";
  /**
   * <code>string description = 2;</code>
   *
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 2;</code>
   *
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BUCKET_FIELD_NUMBER = 3;

  @SuppressWarnings("serial")
  private volatile java.lang.Object bucket_ = "";
  /**
   * <code>string bucket = 3;</code>
   *
   * @return The bucket.
   */
  @java.lang.Override
  public java.lang.String getBucket() {
    java.lang.Object ref = bucket_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bucket_ = s;
      return s;
    }
  }
  /**
   * <code>string bucket = 3;</code>
   *
   * @return The bytes for bucket.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getBucketBytes() {
    java.lang.Object ref = bucket_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      bucket_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OBJECT_FIELD_NUMBER = 4;

  @SuppressWarnings("serial")
  private volatile java.lang.Object object_ = "";
  /**
   * <code>string object = 4;</code>
   *
   * @return The object.
   */
  @java.lang.Override
  public java.lang.String getObject() {
    java.lang.Object ref = object_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      object_ = s;
      return s;
    }
  }
  /**
   * <code>string object = 4;</code>
   *
   * @return The bytes for object.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getObjectBytes() {
    java.lang.Object ref = object_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      object_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int METHOD_FIELD_NUMBER = 5;

  @SuppressWarnings("serial")
  private volatile java.lang.Object method_ = "";
  /**
   * <code>string method = 5;</code>
   *
   * @return The method.
   */
  @java.lang.Override
  public java.lang.String getMethod() {
    java.lang.Object ref = method_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      method_ = s;
      return s;
    }
  }
  /**
   * <code>string method = 5;</code>
   *
   * @return The bytes for method.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getMethodBytes() {
    java.lang.Object ref = method_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      method_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXPIRATION_FIELD_NUMBER = 6;
  private long expiration_ = 0L;
  /**
   * <code>int64 expiration = 6;</code>
   *
   * @return The expiration.
   */
  @java.lang.Override
  public long getExpiration() {
    return expiration_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 7;
  private com.google.protobuf.Timestamp timestamp_;
  /**
   * <code>.google.protobuf.Timestamp timestamp = 7;</code>
   *
   * @return Whether the timestamp field is set.
   */
  @java.lang.Override
  public boolean hasTimestamp() {
    return timestamp_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp timestamp = 7;</code>
   *
   * @return The timestamp.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getTimestamp() {
    return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
  }
  /** <code>.google.protobuf.Timestamp timestamp = 7;</code> */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
    return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
  }

  public static final int EXPECTEDURL_FIELD_NUMBER = 8;

  @SuppressWarnings("serial")
  private volatile java.lang.Object expectedUrl_ = "";
  /**
   * <code>string expectedUrl = 8;</code>
   *
   * @return The expectedUrl.
   */
  @java.lang.Override
  public java.lang.String getExpectedUrl() {
    java.lang.Object ref = expectedUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      expectedUrl_ = s;
      return s;
    }
  }
  /**
   * <code>string expectedUrl = 8;</code>
   *
   * @return The bytes for expectedUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getExpectedUrlBytes() {
    java.lang.Object ref = expectedUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      expectedUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HEADERS_FIELD_NUMBER = 9;

  private static final class HeadersDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<java.lang.String, java.lang.String> defaultEntry =
        com.google.protobuf.MapEntry.<java.lang.String, java.lang.String>newDefaultInstance(
            com.google.cloud.conformance.storage.v1.Tests
                .internal_static_google_cloud_conformance_storage_v1_SigningV4Test_HeadersEntry_descriptor,
            com.google.protobuf.WireFormat.FieldType.STRING,
            "",
            com.google.protobuf.WireFormat.FieldType.STRING,
            "");
  }

  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<java.lang.String, java.lang.String> headers_;

  private com.google.protobuf.MapField<java.lang.String, java.lang.String> internalGetHeaders() {
    if (headers_ == null) {
      return com.google.protobuf.MapField.emptyMapField(HeadersDefaultEntryHolder.defaultEntry);
    }
    return headers_;
  }

  public int getHeadersCount() {
    return internalGetHeaders().getMap().size();
  }
  /** <code>map&lt;string, string&gt; headers = 9;</code> */
  @java.lang.Override
  public boolean containsHeaders(java.lang.String key) {
    if (key == null) {
      throw new NullPointerException("map key");
    }
    return internalGetHeaders().getMap().containsKey(key);
  }
  /** Use {@link #getHeadersMap()} instead. */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getHeaders() {
    return getHeadersMap();
  }
  /** <code>map&lt;string, string&gt; headers = 9;</code> */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getHeadersMap() {
    return internalGetHeaders().getMap();
  }
  /** <code>map&lt;string, string&gt; headers = 9;</code> */
  @java.lang.Override
  public /* nullable */ java.lang.String getHeadersOrDefault(
      java.lang.String key,
      /* nullable */
      java.lang.String defaultValue) {
    if (key == null) {
      throw new NullPointerException("map key");
    }
    java.util.Map<java.lang.String, java.lang.String> map = internalGetHeaders().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /** <code>map&lt;string, string&gt; headers = 9;</code> */
  @java.lang.Override
  public java.lang.String getHeadersOrThrow(java.lang.String key) {
    if (key == null) {
      throw new NullPointerException("map key");
    }
    java.util.Map<java.lang.String, java.lang.String> map = internalGetHeaders().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int QUERY_PARAMETERS_FIELD_NUMBER = 10;

  private static final class QueryParametersDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<java.lang.String, java.lang.String> defaultEntry =
        com.google.protobuf.MapEntry.<java.lang.String, java.lang.String>newDefaultInstance(
            com.google.cloud.conformance.storage.v1.Tests
                .internal_static_google_cloud_conformance_storage_v1_SigningV4Test_QueryParametersEntry_descriptor,
            com.google.protobuf.WireFormat.FieldType.STRING,
            "",
            com.google.protobuf.WireFormat.FieldType.STRING,
            "");
  }

  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<java.lang.String, java.lang.String> queryParameters_;

  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetQueryParameters() {
    if (queryParameters_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          QueryParametersDefaultEntryHolder.defaultEntry);
    }
    return queryParameters_;
  }

  public int getQueryParametersCount() {
    return internalGetQueryParameters().getMap().size();
  }
  /** <code>map&lt;string, string&gt; query_parameters = 10;</code> */
  @java.lang.Override
  public boolean containsQueryParameters(java.lang.String key) {
    if (key == null) {
      throw new NullPointerException("map key");
    }
    return internalGetQueryParameters().getMap().containsKey(key);
  }
  /** Use {@link #getQueryParametersMap()} instead. */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getQueryParameters() {
    return getQueryParametersMap();
  }
  /** <code>map&lt;string, string&gt; query_parameters = 10;</code> */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getQueryParametersMap() {
    return internalGetQueryParameters().getMap();
  }
  /** <code>map&lt;string, string&gt; query_parameters = 10;</code> */
  @java.lang.Override
  public /* nullable */ java.lang.String getQueryParametersOrDefault(
      java.lang.String key,
      /* nullable */
      java.lang.String defaultValue) {
    if (key == null) {
      throw new NullPointerException("map key");
    }
    java.util.Map<java.lang.String, java.lang.String> map = internalGetQueryParameters().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /** <code>map&lt;string, string&gt; query_parameters = 10;</code> */
  @java.lang.Override
  public java.lang.String getQueryParametersOrThrow(java.lang.String key) {
    if (key == null) {
      throw new NullPointerException("map key");
    }
    java.util.Map<java.lang.String, java.lang.String> map = internalGetQueryParameters().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int SCHEME_FIELD_NUMBER = 11;

  @SuppressWarnings("serial")
  private volatile java.lang.Object scheme_ = "";
  /**
   * <code>string scheme = 11;</code>
   *
   * @return The scheme.
   */
  @java.lang.Override
  public java.lang.String getScheme() {
    java.lang.Object ref = scheme_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      scheme_ = s;
      return s;
    }
  }
  /**
   * <code>string scheme = 11;</code>
   *
   * @return The bytes for scheme.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getSchemeBytes() {
    java.lang.Object ref = scheme_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      scheme_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int URLSTYLE_FIELD_NUMBER = 12;
  private int urlStyle_ = 0;
  /**
   * <code>.google.cloud.conformance.storage.v1.UrlStyle urlStyle = 12;</code>
   *
   * @return The enum numeric value on the wire for urlStyle.
   */
  @java.lang.Override
  public int getUrlStyleValue() {
    return urlStyle_;
  }
  /**
   * <code>.google.cloud.conformance.storage.v1.UrlStyle urlStyle = 12;</code>
   *
   * @return The urlStyle.
   */
  @java.lang.Override
  public com.google.cloud.conformance.storage.v1.UrlStyle getUrlStyle() {
    com.google.cloud.conformance.storage.v1.UrlStyle result =
        com.google.cloud.conformance.storage.v1.UrlStyle.forNumber(urlStyle_);
    return result == null ? com.google.cloud.conformance.storage.v1.UrlStyle.UNRECOGNIZED : result;
  }

  public static final int BUCKETBOUNDHOSTNAME_FIELD_NUMBER = 13;

  @SuppressWarnings("serial")
  private volatile java.lang.Object bucketBoundHostname_ = "";
  /**
   * <code>string bucketBoundHostname = 13;</code>
   *
   * @return The bucketBoundHostname.
   */
  @java.lang.Override
  public java.lang.String getBucketBoundHostname() {
    java.lang.Object ref = bucketBoundHostname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bucketBoundHostname_ = s;
      return s;
    }
  }
  /**
   * <code>string bucketBoundHostname = 13;</code>
   *
   * @return The bytes for bucketBoundHostname.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getBucketBoundHostnameBytes() {
    java.lang.Object ref = bucketBoundHostname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      bucketBoundHostname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXPECTEDCANONICALREQUEST_FIELD_NUMBER = 14;

  @SuppressWarnings("serial")
  private volatile java.lang.Object expectedCanonicalRequest_ = "";
  /**
   * <code>string expectedCanonicalRequest = 14;</code>
   *
   * @return The expectedCanonicalRequest.
   */
  @java.lang.Override
  public java.lang.String getExpectedCanonicalRequest() {
    java.lang.Object ref = expectedCanonicalRequest_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      expectedCanonicalRequest_ = s;
      return s;
    }
  }
  /**
   * <code>string expectedCanonicalRequest = 14;</code>
   *
   * @return The bytes for expectedCanonicalRequest.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getExpectedCanonicalRequestBytes() {
    java.lang.Object ref = expectedCanonicalRequest_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      expectedCanonicalRequest_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXPECTEDSTRINGTOSIGN_FIELD_NUMBER = 15;

  @SuppressWarnings("serial")
  private volatile java.lang.Object expectedStringToSign_ = "";
  /**
   * <code>string expectedStringToSign = 15;</code>
   *
   * @return The expectedStringToSign.
   */
  @java.lang.Override
  public java.lang.String getExpectedStringToSign() {
    java.lang.Object ref = expectedStringToSign_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      expectedStringToSign_ = s;
      return s;
    }
  }
  /**
   * <code>string expectedStringToSign = 15;</code>
   *
   * @return The bytes for expectedStringToSign.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getExpectedStringToSignBytes() {
    java.lang.Object ref = expectedStringToSign_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      expectedStringToSign_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fileName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, description_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bucket_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, bucket_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(object_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, object_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(method_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, method_);
    }
    if (expiration_ != 0L) {
      output.writeInt64(6, expiration_);
    }
    if (timestamp_ != null) {
      output.writeMessage(7, getTimestamp());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(expectedUrl_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, expectedUrl_);
    }
    com.google.protobuf.GeneratedMessageV3.serializeStringMapTo(
        output, internalGetHeaders(), HeadersDefaultEntryHolder.defaultEntry, 9);
    com.google.protobuf.GeneratedMessageV3.serializeStringMapTo(
        output, internalGetQueryParameters(), QueryParametersDefaultEntryHolder.defaultEntry, 10);
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(scheme_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, scheme_);
    }
    if (urlStyle_ != com.google.cloud.conformance.storage.v1.UrlStyle.PATH_STYLE.getNumber()) {
      output.writeEnum(12, urlStyle_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bucketBoundHostname_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, bucketBoundHostname_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(expectedCanonicalRequest_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, expectedCanonicalRequest_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(expectedStringToSign_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 15, expectedStringToSign_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fileName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, description_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bucket_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, bucket_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(object_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, object_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(method_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, method_);
    }
    if (expiration_ != 0L) {
      size += com.google.protobuf.CodedOutputStream.computeInt64Size(6, expiration_);
    }
    if (timestamp_ != null) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(7, getTimestamp());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(expectedUrl_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, expectedUrl_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry :
        internalGetHeaders().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String> headers__ =
          HeadersDefaultEntryHolder.defaultEntry
              .newBuilderForType()
              .setKey(entry.getKey())
              .setValue(entry.getValue())
              .build();
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(9, headers__);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry :
        internalGetQueryParameters().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String> queryParameters__ =
          QueryParametersDefaultEntryHolder.defaultEntry
              .newBuilderForType()
              .setKey(entry.getKey())
              .setValue(entry.getValue())
              .build();
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(10, queryParameters__);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(scheme_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, scheme_);
    }
    if (urlStyle_ != com.google.cloud.conformance.storage.v1.UrlStyle.PATH_STYLE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream.computeEnumSize(12, urlStyle_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bucketBoundHostname_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, bucketBoundHostname_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(expectedCanonicalRequest_)) {
      size +=
          com.google.protobuf.GeneratedMessageV3.computeStringSize(14, expectedCanonicalRequest_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(expectedStringToSign_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, expectedStringToSign_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof com.google.cloud.conformance.storage.v1.SigningV4Test)) {
      return super.equals(obj);
    }
    com.google.cloud.conformance.storage.v1.SigningV4Test other =
        (com.google.cloud.conformance.storage.v1.SigningV4Test) obj;

    if (!getFileName().equals(other.getFileName())) return false;
    if (!getDescription().equals(other.getDescription())) return false;
    if (!getBucket().equals(other.getBucket())) return false;
    if (!getObject().equals(other.getObject())) return false;
    if (!getMethod().equals(other.getMethod())) return false;
    if (getExpiration() != other.getExpiration()) return false;
    if (hasTimestamp() != other.hasTimestamp()) return false;
    if (hasTimestamp()) {
      if (!getTimestamp().equals(other.getTimestamp())) return false;
    }
    if (!getExpectedUrl().equals(other.getExpectedUrl())) return false;
    if (!internalGetHeaders().equals(other.internalGetHeaders())) return false;
    if (!internalGetQueryParameters().equals(other.internalGetQueryParameters())) return false;
    if (!getScheme().equals(other.getScheme())) return false;
    if (urlStyle_ != other.urlStyle_) return false;
    if (!getBucketBoundHostname().equals(other.getBucketBoundHostname())) return false;
    if (!getExpectedCanonicalRequest().equals(other.getExpectedCanonicalRequest())) return false;
    if (!getExpectedStringToSign().equals(other.getExpectedStringToSign())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FILENAME_FIELD_NUMBER;
    hash = (53 * hash) + getFileName().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + BUCKET_FIELD_NUMBER;
    hash = (53 * hash) + getBucket().hashCode();
    hash = (37 * hash) + OBJECT_FIELD_NUMBER;
    hash = (53 * hash) + getObject().hashCode();
    hash = (37 * hash) + METHOD_FIELD_NUMBER;
    hash = (53 * hash) + getMethod().hashCode();
    hash = (37 * hash) + EXPIRATION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getExpiration());
    if (hasTimestamp()) {
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
    }
    hash = (37 * hash) + EXPECTEDURL_FIELD_NUMBER;
    hash = (53 * hash) + getExpectedUrl().hashCode();
    if (!internalGetHeaders().getMap().isEmpty()) {
      hash = (37 * hash) + HEADERS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetHeaders().hashCode();
    }
    if (!internalGetQueryParameters().getMap().isEmpty()) {
      hash = (37 * hash) + QUERY_PARAMETERS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetQueryParameters().hashCode();
    }
    hash = (37 * hash) + SCHEME_FIELD_NUMBER;
    hash = (53 * hash) + getScheme().hashCode();
    hash = (37 * hash) + URLSTYLE_FIELD_NUMBER;
    hash = (53 * hash) + urlStyle_;
    hash = (37 * hash) + BUCKETBOUNDHOSTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getBucketBoundHostname().hashCode();
    hash = (37 * hash) + EXPECTEDCANONICALREQUEST_FIELD_NUMBER;
    hash = (53 * hash) + getExpectedCanonicalRequest().hashCode();
    hash = (37 * hash) + EXPECTEDSTRINGTOSIGN_FIELD_NUMBER;
    hash = (53 * hash) + getExpectedStringToSign().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.cloud.conformance.storage.v1.SigningV4Test parseFrom(
      java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.cloud.conformance.storage.v1.SigningV4Test parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.cloud.conformance.storage.v1.SigningV4Test parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.cloud.conformance.storage.v1.SigningV4Test parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.cloud.conformance.storage.v1.SigningV4Test parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.cloud.conformance.storage.v1.SigningV4Test parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.cloud.conformance.storage.v1.SigningV4Test parseFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.google.cloud.conformance.storage.v1.SigningV4Test parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.google.cloud.conformance.storage.v1.SigningV4Test parseDelimitedFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.cloud.conformance.storage.v1.SigningV4Test parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.google.cloud.conformance.storage.v1.SigningV4Test parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.google.cloud.conformance.storage.v1.SigningV4Test parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(
      com.google.cloud.conformance.storage.v1.SigningV4Test prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /** Protobuf type {@code google.cloud.conformance.storage.v1.SigningV4Test} */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:google.cloud.conformance.storage.v1.SigningV4Test)
      com.google.cloud.conformance.storage.v1.SigningV4TestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.google.cloud.conformance.storage.v1.Tests
          .internal_static_google_cloud_conformance_storage_v1_SigningV4Test_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(int number) {
      switch (number) {
        case 9:
          return internalGetHeaders();
        case 10:
          return internalGetQueryParameters();
        default:
          throw new RuntimeException("Invalid map field number: " + number);
      }
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(int number) {
      switch (number) {
        case 9:
          return internalGetMutableHeaders();
        case 10:
          return internalGetMutableQueryParameters();
        default:
          throw new RuntimeException("Invalid map field number: " + number);
      }
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.cloud.conformance.storage.v1.Tests
          .internal_static_google_cloud_conformance_storage_v1_SigningV4Test_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.cloud.conformance.storage.v1.SigningV4Test.class,
              com.google.cloud.conformance.storage.v1.SigningV4Test.Builder.class);
    }

    // Construct using com.google.cloud.conformance.storage.v1.SigningV4Test.newBuilder()
    private Builder() {}

    private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      fileName_ = "";
      description_ = "";
      bucket_ = "";
      object_ = "";
      method_ = "";
      expiration_ = 0L;
      timestamp_ = null;
      if (timestampBuilder_ != null) {
        timestampBuilder_.dispose();
        timestampBuilder_ = null;
      }
      expectedUrl_ = "";
      internalGetMutableHeaders().clear();
      internalGetMutableQueryParameters().clear();
      scheme_ = "";
      urlStyle_ = 0;
      bucketBoundHostname_ = "";
      expectedCanonicalRequest_ = "";
      expectedStringToSign_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return com.google.cloud.conformance.storage.v1.Tests
          .internal_static_google_cloud_conformance_storage_v1_SigningV4Test_descriptor;
    }

    @java.lang.Override
    public com.google.cloud.conformance.storage.v1.SigningV4Test getDefaultInstanceForType() {
      return com.google.cloud.conformance.storage.v1.SigningV4Test.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.cloud.conformance.storage.v1.SigningV4Test build() {
      com.google.cloud.conformance.storage.v1.SigningV4Test result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.cloud.conformance.storage.v1.SigningV4Test buildPartial() {
      com.google.cloud.conformance.storage.v1.SigningV4Test result =
          new com.google.cloud.conformance.storage.v1.SigningV4Test(this);
      if (bitField0_ != 0) {
        buildPartial0(result);
      }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.cloud.conformance.storage.v1.SigningV4Test result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.fileName_ = fileName_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.description_ = description_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.bucket_ = bucket_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.object_ = object_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.method_ = method_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.expiration_ = expiration_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.timestamp_ = timestampBuilder_ == null ? timestamp_ : timestampBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.expectedUrl_ = expectedUrl_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.headers_ = internalGetHeaders();
        result.headers_.makeImmutable();
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.queryParameters_ = internalGetQueryParameters();
        result.queryParameters_.makeImmutable();
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.scheme_ = scheme_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.urlStyle_ = urlStyle_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.bucketBoundHostname_ = bucketBoundHostname_;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.expectedCanonicalRequest_ = expectedCanonicalRequest_;
      }
      if (((from_bitField0_ & 0x00004000) != 0)) {
        result.expectedStringToSign_ = expectedStringToSign_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.cloud.conformance.storage.v1.SigningV4Test) {
        return mergeFrom((com.google.cloud.conformance.storage.v1.SigningV4Test) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.cloud.conformance.storage.v1.SigningV4Test other) {
      if (other == com.google.cloud.conformance.storage.v1.SigningV4Test.getDefaultInstance())
        return this;
      if (!other.getFileName().isEmpty()) {
        fileName_ = other.fileName_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getBucket().isEmpty()) {
        bucket_ = other.bucket_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getObject().isEmpty()) {
        object_ = other.object_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getMethod().isEmpty()) {
        method_ = other.method_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getExpiration() != 0L) {
        setExpiration(other.getExpiration());
      }
      if (other.hasTimestamp()) {
        mergeTimestamp(other.getTimestamp());
      }
      if (!other.getExpectedUrl().isEmpty()) {
        expectedUrl_ = other.expectedUrl_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      internalGetMutableHeaders().mergeFrom(other.internalGetHeaders());
      bitField0_ |= 0x00000100;
      internalGetMutableQueryParameters().mergeFrom(other.internalGetQueryParameters());
      bitField0_ |= 0x00000200;
      if (!other.getScheme().isEmpty()) {
        scheme_ = other.scheme_;
        bitField0_ |= 0x00000400;
        onChanged();
      }
      if (other.urlStyle_ != 0) {
        setUrlStyleValue(other.getUrlStyleValue());
      }
      if (!other.getBucketBoundHostname().isEmpty()) {
        bucketBoundHostname_ = other.bucketBoundHostname_;
        bitField0_ |= 0x00001000;
        onChanged();
      }
      if (!other.getExpectedCanonicalRequest().isEmpty()) {
        expectedCanonicalRequest_ = other.expectedCanonicalRequest_;
        bitField0_ |= 0x00002000;
        onChanged();
      }
      if (!other.getExpectedStringToSign().isEmpty()) {
        expectedStringToSign_ = other.expectedStringToSign_;
        bitField0_ |= 0x00004000;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10:
              {
                fileName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
            case 18:
              {
                description_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
            case 26:
              {
                bucket_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
            case 34:
              {
                object_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
            case 42:
              {
                method_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
            case 48:
              {
                expiration_ = input.readInt64();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
            case 58:
              {
                input.readMessage(getTimestampFieldBuilder().getBuilder(), extensionRegistry);
                bitField0_ |= 0x00000040;
                break;
              } // case 58
            case 66:
              {
                expectedUrl_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
            case 74:
              {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String> headers__ =
                    input.readMessage(
                        HeadersDefaultEntryHolder.defaultEntry.getParserForType(),
                        extensionRegistry);
                internalGetMutableHeaders()
                    .getMutableMap()
                    .put(headers__.getKey(), headers__.getValue());
                bitField0_ |= 0x00000100;
                break;
              } // case 74
            case 82:
              {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String> queryParameters__ =
                    input.readMessage(
                        QueryParametersDefaultEntryHolder.defaultEntry.getParserForType(),
                        extensionRegistry);
                internalGetMutableQueryParameters()
                    .getMutableMap()
                    .put(queryParameters__.getKey(), queryParameters__.getValue());
                bitField0_ |= 0x00000200;
                break;
              } // case 82
            case 90:
              {
                scheme_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000400;
                break;
              } // case 90
            case 96:
              {
                urlStyle_ = input.readEnum();
                bitField0_ |= 0x00000800;
                break;
              } // case 96
            case 106:
              {
                bucketBoundHostname_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00001000;
                break;
              } // case 106
            case 114:
              {
                expectedCanonicalRequest_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00002000;
                break;
              } // case 114
            case 122:
              {
                expectedStringToSign_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00004000;
                break;
              } // case 122
            default:
              {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private int bitField0_;

    private java.lang.Object fileName_ = "";
    /**
     * <code>string fileName = 1;</code>
     *
     * @return The fileName.
     */
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string fileName = 1;</code>
     *
     * @return The bytes for fileName.
     */
    public com.google.protobuf.ByteString getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string fileName = 1;</code>
     *
     * @param value The fileName to set.
     * @return This builder for chaining.
     */
    public Builder setFileName(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      fileName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string fileName = 1;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearFileName() {
      fileName_ = getDefaultInstance().getFileName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string fileName = 1;</code>
     *
     * @param value The bytes for fileName to set.
     * @return This builder for chaining.
     */
    public Builder setFileNameBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      fileName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 2;</code>
     *
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 2;</code>
     *
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 2;</code>
     *
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      description_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 2;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      description_ = getDefaultInstance().getDescription();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string description = 2;</code>
     *
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      description_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object bucket_ = "";
    /**
     * <code>string bucket = 3;</code>
     *
     * @return The bucket.
     */
    public java.lang.String getBucket() {
      java.lang.Object ref = bucket_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bucket_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string bucket = 3;</code>
     *
     * @return The bytes for bucket.
     */
    public com.google.protobuf.ByteString getBucketBytes() {
      java.lang.Object ref = bucket_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        bucket_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string bucket = 3;</code>
     *
     * @param value The bucket to set.
     * @return This builder for chaining.
     */
    public Builder setBucket(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bucket_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string bucket = 3;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearBucket() {
      bucket_ = getDefaultInstance().getBucket();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string bucket = 3;</code>
     *
     * @param value The bytes for bucket to set.
     * @return This builder for chaining.
     */
    public Builder setBucketBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      bucket_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object object_ = "";
    /**
     * <code>string object = 4;</code>
     *
     * @return The object.
     */
    public java.lang.String getObject() {
      java.lang.Object ref = object_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        object_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string object = 4;</code>
     *
     * @return The bytes for object.
     */
    public com.google.protobuf.ByteString getObjectBytes() {
      java.lang.Object ref = object_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        object_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string object = 4;</code>
     *
     * @param value The object to set.
     * @return This builder for chaining.
     */
    public Builder setObject(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      object_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string object = 4;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearObject() {
      object_ = getDefaultInstance().getObject();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string object = 4;</code>
     *
     * @param value The bytes for object to set.
     * @return This builder for chaining.
     */
    public Builder setObjectBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      object_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object method_ = "";
    /**
     * <code>string method = 5;</code>
     *
     * @return The method.
     */
    public java.lang.String getMethod() {
      java.lang.Object ref = method_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        method_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string method = 5;</code>
     *
     * @return The bytes for method.
     */
    public com.google.protobuf.ByteString getMethodBytes() {
      java.lang.Object ref = method_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        method_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string method = 5;</code>
     *
     * @param value The method to set.
     * @return This builder for chaining.
     */
    public Builder setMethod(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      method_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string method = 5;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearMethod() {
      method_ = getDefaultInstance().getMethod();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string method = 5;</code>
     *
     * @param value The bytes for method to set.
     * @return This builder for chaining.
     */
    public Builder setMethodBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      method_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private long expiration_;
    /**
     * <code>int64 expiration = 6;</code>
     *
     * @return The expiration.
     */
    @java.lang.Override
    public long getExpiration() {
      return expiration_;
    }
    /**
     * <code>int64 expiration = 6;</code>
     *
     * @param value The expiration to set.
     * @return This builder for chaining.
     */
    public Builder setExpiration(long value) {

      expiration_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int64 expiration = 6;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearExpiration() {
      bitField0_ = (bitField0_ & ~0x00000020);
      expiration_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp timestamp_;
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp,
            com.google.protobuf.Timestamp.Builder,
            com.google.protobuf.TimestampOrBuilder>
        timestampBuilder_;
    /**
     * <code>.google.protobuf.Timestamp timestamp = 7;</code>
     *
     * @return Whether the timestamp field is set.
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 7;</code>
     *
     * @return The timestamp.
     */
    public com.google.protobuf.Timestamp getTimestamp() {
      if (timestampBuilder_ == null) {
        return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      } else {
        return timestampBuilder_.getMessage();
      }
    }
    /** <code>.google.protobuf.Timestamp timestamp = 7;</code> */
    public Builder setTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timestamp_ = value;
      } else {
        timestampBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /** <code>.google.protobuf.Timestamp timestamp = 7;</code> */
    public Builder setTimestamp(com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timestampBuilder_ == null) {
        timestamp_ = builderForValue.build();
      } else {
        timestampBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /** <code>.google.protobuf.Timestamp timestamp = 7;</code> */
    public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0)
            && timestamp_ != null
            && timestamp_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getTimestampBuilder().mergeFrom(value);
        } else {
          timestamp_ = value;
        }
      } else {
        timestampBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /** <code>.google.protobuf.Timestamp timestamp = 7;</code> */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000040);
      timestamp_ = null;
      if (timestampBuilder_ != null) {
        timestampBuilder_.dispose();
        timestampBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /** <code>.google.protobuf.Timestamp timestamp = 7;</code> */
    public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getTimestampFieldBuilder().getBuilder();
    }
    /** <code>.google.protobuf.Timestamp timestamp = 7;</code> */
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      if (timestampBuilder_ != null) {
        return timestampBuilder_.getMessageOrBuilder();
      } else {
        return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      }
    }
    /** <code>.google.protobuf.Timestamp timestamp = 7;</code> */
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp,
            com.google.protobuf.Timestamp.Builder,
            com.google.protobuf.TimestampOrBuilder>
        getTimestampFieldBuilder() {
      if (timestampBuilder_ == null) {
        timestampBuilder_ =
            new com.google.protobuf.SingleFieldBuilderV3<
                com.google.protobuf.Timestamp,
                com.google.protobuf.Timestamp.Builder,
                com.google.protobuf.TimestampOrBuilder>(
                getTimestamp(), getParentForChildren(), isClean());
        timestamp_ = null;
      }
      return timestampBuilder_;
    }

    private java.lang.Object expectedUrl_ = "";
    /**
     * <code>string expectedUrl = 8;</code>
     *
     * @return The expectedUrl.
     */
    public java.lang.String getExpectedUrl() {
      java.lang.Object ref = expectedUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        expectedUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string expectedUrl = 8;</code>
     *
     * @return The bytes for expectedUrl.
     */
    public com.google.protobuf.ByteString getExpectedUrlBytes() {
      java.lang.Object ref = expectedUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        expectedUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string expectedUrl = 8;</code>
     *
     * @param value The expectedUrl to set.
     * @return This builder for chaining.
     */
    public Builder setExpectedUrl(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      expectedUrl_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string expectedUrl = 8;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearExpectedUrl() {
      expectedUrl_ = getDefaultInstance().getExpectedUrl();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string expectedUrl = 8;</code>
     *
     * @param value The bytes for expectedUrl to set.
     * @return This builder for chaining.
     */
    public Builder setExpectedUrlBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      expectedUrl_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<java.lang.String, java.lang.String> headers_;

    private com.google.protobuf.MapField<java.lang.String, java.lang.String> internalGetHeaders() {
      if (headers_ == null) {
        return com.google.protobuf.MapField.emptyMapField(HeadersDefaultEntryHolder.defaultEntry);
      }
      return headers_;
    }

    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableHeaders() {
      if (headers_ == null) {
        headers_ = com.google.protobuf.MapField.newMapField(HeadersDefaultEntryHolder.defaultEntry);
      }
      if (!headers_.isMutable()) {
        headers_ = headers_.copy();
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return headers_;
    }

    public int getHeadersCount() {
      return internalGetHeaders().getMap().size();
    }
    /** <code>map&lt;string, string&gt; headers = 9;</code> */
    @java.lang.Override
    public boolean containsHeaders(java.lang.String key) {
      if (key == null) {
        throw new NullPointerException("map key");
      }
      return internalGetHeaders().getMap().containsKey(key);
    }
    /** Use {@link #getHeadersMap()} instead. */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getHeaders() {
      return getHeadersMap();
    }
    /** <code>map&lt;string, string&gt; headers = 9;</code> */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getHeadersMap() {
      return internalGetHeaders().getMap();
    }
    /** <code>map&lt;string, string&gt; headers = 9;</code> */
    @java.lang.Override
    public /* nullable */ java.lang.String getHeadersOrDefault(
        java.lang.String key,
        /* nullable */
        java.lang.String defaultValue) {
      if (key == null) {
        throw new NullPointerException("map key");
      }
      java.util.Map<java.lang.String, java.lang.String> map = internalGetHeaders().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /** <code>map&lt;string, string&gt; headers = 9;</code> */
    @java.lang.Override
    public java.lang.String getHeadersOrThrow(java.lang.String key) {
      if (key == null) {
        throw new NullPointerException("map key");
      }
      java.util.Map<java.lang.String, java.lang.String> map = internalGetHeaders().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearHeaders() {
      bitField0_ = (bitField0_ & ~0x00000100);
      internalGetMutableHeaders().getMutableMap().clear();
      return this;
    }
    /** <code>map&lt;string, string&gt; headers = 9;</code> */
    public Builder removeHeaders(java.lang.String key) {
      if (key == null) {
        throw new NullPointerException("map key");
      }
      internalGetMutableHeaders().getMutableMap().remove(key);
      return this;
    }
    /** Use alternate mutation accessors instead. */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMutableHeaders() {
      bitField0_ |= 0x00000100;
      return internalGetMutableHeaders().getMutableMap();
    }
    /** <code>map&lt;string, string&gt; headers = 9;</code> */
    public Builder putHeaders(java.lang.String key, java.lang.String value) {
      if (key == null) {
        throw new NullPointerException("map key");
      }
      if (value == null) {
        throw new NullPointerException("map value");
      }
      internalGetMutableHeaders().getMutableMap().put(key, value);
      bitField0_ |= 0x00000100;
      return this;
    }
    /** <code>map&lt;string, string&gt; headers = 9;</code> */
    public Builder putAllHeaders(java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableHeaders().getMutableMap().putAll(values);
      bitField0_ |= 0x00000100;
      return this;
    }

    private com.google.protobuf.MapField<java.lang.String, java.lang.String> queryParameters_;

    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetQueryParameters() {
      if (queryParameters_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            QueryParametersDefaultEntryHolder.defaultEntry);
      }
      return queryParameters_;
    }

    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableQueryParameters() {
      if (queryParameters_ == null) {
        queryParameters_ =
            com.google.protobuf.MapField.newMapField(
                QueryParametersDefaultEntryHolder.defaultEntry);
      }
      if (!queryParameters_.isMutable()) {
        queryParameters_ = queryParameters_.copy();
      }
      bitField0_ |= 0x00000200;
      onChanged();
      return queryParameters_;
    }

    public int getQueryParametersCount() {
      return internalGetQueryParameters().getMap().size();
    }
    /** <code>map&lt;string, string&gt; query_parameters = 10;</code> */
    @java.lang.Override
    public boolean containsQueryParameters(java.lang.String key) {
      if (key == null) {
        throw new NullPointerException("map key");
      }
      return internalGetQueryParameters().getMap().containsKey(key);
    }
    /** Use {@link #getQueryParametersMap()} instead. */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getQueryParameters() {
      return getQueryParametersMap();
    }
    /** <code>map&lt;string, string&gt; query_parameters = 10;</code> */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getQueryParametersMap() {
      return internalGetQueryParameters().getMap();
    }
    /** <code>map&lt;string, string&gt; query_parameters = 10;</code> */
    @java.lang.Override
    public /* nullable */ java.lang.String getQueryParametersOrDefault(
        java.lang.String key,
        /* nullable */
        java.lang.String defaultValue) {
      if (key == null) {
        throw new NullPointerException("map key");
      }
      java.util.Map<java.lang.String, java.lang.String> map = internalGetQueryParameters().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /** <code>map&lt;string, string&gt; query_parameters = 10;</code> */
    @java.lang.Override
    public java.lang.String getQueryParametersOrThrow(java.lang.String key) {
      if (key == null) {
        throw new NullPointerException("map key");
      }
      java.util.Map<java.lang.String, java.lang.String> map = internalGetQueryParameters().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearQueryParameters() {
      bitField0_ = (bitField0_ & ~0x00000200);
      internalGetMutableQueryParameters().getMutableMap().clear();
      return this;
    }
    /** <code>map&lt;string, string&gt; query_parameters = 10;</code> */
    public Builder removeQueryParameters(java.lang.String key) {
      if (key == null) {
        throw new NullPointerException("map key");
      }
      internalGetMutableQueryParameters().getMutableMap().remove(key);
      return this;
    }
    /** Use alternate mutation accessors instead. */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMutableQueryParameters() {
      bitField0_ |= 0x00000200;
      return internalGetMutableQueryParameters().getMutableMap();
    }
    /** <code>map&lt;string, string&gt; query_parameters = 10;</code> */
    public Builder putQueryParameters(java.lang.String key, java.lang.String value) {
      if (key == null) {
        throw new NullPointerException("map key");
      }
      if (value == null) {
        throw new NullPointerException("map value");
      }
      internalGetMutableQueryParameters().getMutableMap().put(key, value);
      bitField0_ |= 0x00000200;
      return this;
    }
    /** <code>map&lt;string, string&gt; query_parameters = 10;</code> */
    public Builder putAllQueryParameters(java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableQueryParameters().getMutableMap().putAll(values);
      bitField0_ |= 0x00000200;
      return this;
    }

    private java.lang.Object scheme_ = "";
    /**
     * <code>string scheme = 11;</code>
     *
     * @return The scheme.
     */
    public java.lang.String getScheme() {
      java.lang.Object ref = scheme_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        scheme_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string scheme = 11;</code>
     *
     * @return The bytes for scheme.
     */
    public com.google.protobuf.ByteString getSchemeBytes() {
      java.lang.Object ref = scheme_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        scheme_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string scheme = 11;</code>
     *
     * @param value The scheme to set.
     * @return This builder for chaining.
     */
    public Builder setScheme(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      scheme_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>string scheme = 11;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearScheme() {
      scheme_ = getDefaultInstance().getScheme();
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }
    /**
     * <code>string scheme = 11;</code>
     *
     * @param value The bytes for scheme to set.
     * @return This builder for chaining.
     */
    public Builder setSchemeBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      scheme_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }

    private int urlStyle_ = 0;
    /**
     * <code>.google.cloud.conformance.storage.v1.UrlStyle urlStyle = 12;</code>
     *
     * @return The enum numeric value on the wire for urlStyle.
     */
    @java.lang.Override
    public int getUrlStyleValue() {
      return urlStyle_;
    }
    /**
     * <code>.google.cloud.conformance.storage.v1.UrlStyle urlStyle = 12;</code>
     *
     * @param value The enum numeric value on the wire for urlStyle to set.
     * @return This builder for chaining.
     */
    public Builder setUrlStyleValue(int value) {
      urlStyle_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>.google.cloud.conformance.storage.v1.UrlStyle urlStyle = 12;</code>
     *
     * @return The urlStyle.
     */
    @java.lang.Override
    public com.google.cloud.conformance.storage.v1.UrlStyle getUrlStyle() {
      com.google.cloud.conformance.storage.v1.UrlStyle result =
          com.google.cloud.conformance.storage.v1.UrlStyle.forNumber(urlStyle_);
      return result == null
          ? com.google.cloud.conformance.storage.v1.UrlStyle.UNRECOGNIZED
          : result;
    }
    /**
     * <code>.google.cloud.conformance.storage.v1.UrlStyle urlStyle = 12;</code>
     *
     * @param value The urlStyle to set.
     * @return This builder for chaining.
     */
    public Builder setUrlStyle(com.google.cloud.conformance.storage.v1.UrlStyle value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000800;
      urlStyle_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.google.cloud.conformance.storage.v1.UrlStyle urlStyle = 12;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearUrlStyle() {
      bitField0_ = (bitField0_ & ~0x00000800);
      urlStyle_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object bucketBoundHostname_ = "";
    /**
     * <code>string bucketBoundHostname = 13;</code>
     *
     * @return The bucketBoundHostname.
     */
    public java.lang.String getBucketBoundHostname() {
      java.lang.Object ref = bucketBoundHostname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bucketBoundHostname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string bucketBoundHostname = 13;</code>
     *
     * @return The bytes for bucketBoundHostname.
     */
    public com.google.protobuf.ByteString getBucketBoundHostnameBytes() {
      java.lang.Object ref = bucketBoundHostname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        bucketBoundHostname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string bucketBoundHostname = 13;</code>
     *
     * @param value The bucketBoundHostname to set.
     * @return This builder for chaining.
     */
    public Builder setBucketBoundHostname(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bucketBoundHostname_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>string bucketBoundHostname = 13;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearBucketBoundHostname() {
      bucketBoundHostname_ = getDefaultInstance().getBucketBoundHostname();
      bitField0_ = (bitField0_ & ~0x00001000);
      onChanged();
      return this;
    }
    /**
     * <code>string bucketBoundHostname = 13;</code>
     *
     * @param value The bytes for bucketBoundHostname to set.
     * @return This builder for chaining.
     */
    public Builder setBucketBoundHostnameBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      bucketBoundHostname_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }

    private java.lang.Object expectedCanonicalRequest_ = "";
    /**
     * <code>string expectedCanonicalRequest = 14;</code>
     *
     * @return The expectedCanonicalRequest.
     */
    public java.lang.String getExpectedCanonicalRequest() {
      java.lang.Object ref = expectedCanonicalRequest_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        expectedCanonicalRequest_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string expectedCanonicalRequest = 14;</code>
     *
     * @return The bytes for expectedCanonicalRequest.
     */
    public com.google.protobuf.ByteString getExpectedCanonicalRequestBytes() {
      java.lang.Object ref = expectedCanonicalRequest_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        expectedCanonicalRequest_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string expectedCanonicalRequest = 14;</code>
     *
     * @param value The expectedCanonicalRequest to set.
     * @return This builder for chaining.
     */
    public Builder setExpectedCanonicalRequest(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      expectedCanonicalRequest_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <code>string expectedCanonicalRequest = 14;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearExpectedCanonicalRequest() {
      expectedCanonicalRequest_ = getDefaultInstance().getExpectedCanonicalRequest();
      bitField0_ = (bitField0_ & ~0x00002000);
      onChanged();
      return this;
    }
    /**
     * <code>string expectedCanonicalRequest = 14;</code>
     *
     * @param value The bytes for expectedCanonicalRequest to set.
     * @return This builder for chaining.
     */
    public Builder setExpectedCanonicalRequestBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      expectedCanonicalRequest_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }

    private java.lang.Object expectedStringToSign_ = "";
    /**
     * <code>string expectedStringToSign = 15;</code>
     *
     * @return The expectedStringToSign.
     */
    public java.lang.String getExpectedStringToSign() {
      java.lang.Object ref = expectedStringToSign_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        expectedStringToSign_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string expectedStringToSign = 15;</code>
     *
     * @return The bytes for expectedStringToSign.
     */
    public com.google.protobuf.ByteString getExpectedStringToSignBytes() {
      java.lang.Object ref = expectedStringToSign_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        expectedStringToSign_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string expectedStringToSign = 15;</code>
     *
     * @param value The expectedStringToSign to set.
     * @return This builder for chaining.
     */
    public Builder setExpectedStringToSign(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      expectedStringToSign_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }
    /**
     * <code>string expectedStringToSign = 15;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearExpectedStringToSign() {
      expectedStringToSign_ = getDefaultInstance().getExpectedStringToSign();
      bitField0_ = (bitField0_ & ~0x00004000);
      onChanged();
      return this;
    }
    /**
     * <code>string expectedStringToSign = 15;</code>
     *
     * @param value The bytes for expectedStringToSign to set.
     * @return This builder for chaining.
     */
    public Builder setExpectedStringToSignBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      expectedStringToSign_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }

    @java.lang.Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:google.cloud.conformance.storage.v1.SigningV4Test)
  }

  // @@protoc_insertion_point(class_scope:google.cloud.conformance.storage.v1.SigningV4Test)
  private static final com.google.cloud.conformance.storage.v1.SigningV4Test DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new com.google.cloud.conformance.storage.v1.SigningV4Test();
  }

  public static com.google.cloud.conformance.storage.v1.SigningV4Test getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SigningV4Test> PARSER =
      new com.google.protobuf.AbstractParser<SigningV4Test>() {
        @java.lang.Override
        public SigningV4Test parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

  public static com.google.protobuf.Parser<SigningV4Test> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SigningV4Test> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.cloud.conformance.storage.v1.SigningV4Test getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
