/*
 * Copyright 2019 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/conformance/storage/v1/tests.proto

package com.google.cloud.conformance.storage.v1;

public final class Tests {
  private Tests() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_conformance_storage_v1_TestFile_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_conformance_storage_v1_TestFile_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_conformance_storage_v1_SigningV4Test_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_conformance_storage_v1_SigningV4Test_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_conformance_storage_v1_SigningV4Test_HeadersEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_conformance_storage_v1_SigningV4Test_HeadersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_conformance_storage_v1_SigningV4Test_QueryParametersEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_conformance_storage_v1_SigningV4Test_QueryParametersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_conformance_storage_v1_ConditionalMatches_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_conformance_storage_v1_ConditionalMatches_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_conformance_storage_v1_PolicyConditions_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_conformance_storage_v1_PolicyConditions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_conformance_storage_v1_PolicyInput_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_conformance_storage_v1_PolicyInput_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_conformance_storage_v1_PolicyInput_FieldsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_conformance_storage_v1_PolicyInput_FieldsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_conformance_storage_v1_PolicyOutput_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_conformance_storage_v1_PolicyOutput_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_conformance_storage_v1_PolicyOutput_FieldsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_conformance_storage_v1_PolicyOutput_FieldsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_conformance_storage_v1_PostPolicyV4Test_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_conformance_storage_v1_PostPolicyV4Test_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_conformance_storage_v1_RetryTests_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_conformance_storage_v1_RetryTests_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_conformance_storage_v1_InstructionList_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_conformance_storage_v1_InstructionList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_conformance_storage_v1_Method_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_conformance_storage_v1_Method_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_conformance_storage_v1_RetryTest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_conformance_storage_v1_RetryTest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n/google/cloud/conformance/storage/v1/te"
          + "sts.proto\022#google.cloud.conformance.stor"
          + "age.v1\032\037google/protobuf/timestamp.proto\""
          + "\362\001\n\010TestFile\022L\n\020signing_v4_tests\030\001 \003(\01322"
          + ".google.cloud.conformance.storage.v1.Sig"
          + "ningV4Test\022S\n\024post_policy_v4_tests\030\002 \003(\013"
          + "25.google.cloud.conformance.storage.v1.P"
          + "ostPolicyV4Test\022C\n\013retry_tests\030\003 \003(\0132..g"
          + "oogle.cloud.conformance.storage.v1.Retry"
          + "Test\"\345\005\n\rSigningV4Test\022\020\n\010fileName\030\001 \001(\t"
          + "\022\023\n\013description\030\002 \001(\t\022\016\n\006bucket\030\003 \001(\t\022\016\n"
          + "\006object\030\004 \001(\t\022\016\n\006method\030\005 \001(\t\022\022\n\nexpirat"
          + "ion\030\006 \001(\003\022-\n\ttimestamp\030\007 \001(\0132\032.google.pr"
          + "otobuf.Timestamp\022\023\n\013expectedUrl\030\010 \001(\t\022P\n"
          + "\007headers\030\t \003(\0132?.google.cloud.conformanc"
          + "e.storage.v1.SigningV4Test.HeadersEntry\022"
          + "a\n\020query_parameters\030\n \003(\0132G.google.cloud"
          + ".conformance.storage.v1.SigningV4Test.Qu"
          + "eryParametersEntry\022\016\n\006scheme\030\013 \001(\t\022?\n\010ur"
          + "lStyle\030\014 \001(\0162-.google.cloud.conformance."
          + "storage.v1.UrlStyle\022\033\n\023bucketBoundHostna"
          + "me\030\r \001(\t\022 \n\030expectedCanonicalRequest\030\016 \001"
          + "(\t\022\034\n\024expectedStringToSign\030\017 \001(\t\022\020\n\010host"
          + "name\030\020 \001(\t\022\026\n\016clientEndpoint\030\021 \001(\t\022\030\n\020em"
          + "ulatorHostname\030\022 \001(\t\022\026\n\016universeDomain\030\023"
          + " \001(\t\032.\n\014HeadersEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005val"
          + "ue\030\002 \001(\t:\0028\001\0326\n\024QueryParametersEntry\022\013\n\003"
          + "key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"(\n\022Conditio"
          + "nalMatches\022\022\n\nexpression\030\001 \003(\t\"B\n\020Policy"
          + "Conditions\022\032\n\022contentLengthRange\030\001 \003(\005\022\022"
          + "\n\nstartsWith\030\002 \003(\t\"\246\003\n\013PolicyInput\022\016\n\006sc"
          + "heme\030\001 \001(\t\022?\n\010urlStyle\030\002 \001(\0162-.google.cl"
          + "oud.conformance.storage.v1.UrlStyle\022\033\n\023b"
          + "ucketBoundHostname\030\003 \001(\t\022\016\n\006bucket\030\004 \001(\t"
          + "\022\016\n\006object\030\005 \001(\t\022\022\n\nexpiration\030\006 \001(\005\022-\n\t"
          + "timestamp\030\007 \001(\0132\032.google.protobuf.Timest"
          + "amp\022L\n\006fields\030\010 \003(\0132<.google.cloud.confo"
          + "rmance.storage.v1.PolicyInput.FieldsEntr"
          + "y\022I\n\nconditions\030\t \001(\01325.google.cloud.con"
          + "formance.storage.v1.PolicyConditions\032-\n\013"
          + "FieldsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:"
          + "\0028\001\"\270\001\n\014PolicyOutput\022\013\n\003url\030\001 \001(\t\022M\n\006fie"
          + "lds\030\002 \003(\0132=.google.cloud.conformance.sto"
          + "rage.v1.PolicyOutput.FieldsEntry\022\035\n\025expe"
          + "ctedDecodedPolicy\030\003 \001(\t\032-\n\013FieldsEntry\022\013"
          + "\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\267\001\n\020PostP"
          + "olicyV4Test\022\023\n\013description\030\001 \001(\t\022E\n\013poli"
          + "cyInput\030\002 \001(\01320.google.cloud.conformance"
          + ".storage.v1.PolicyInput\022G\n\014policyOutput\030"
          + "\003 \001(\01321.google.cloud.conformance.storage"
          + ".v1.PolicyOutput\"P\n\nRetryTests\022B\n\nretryT"
          + "ests\030\001 \003(\0132..google.cloud.conformance.st"
          + "orage.v1.RetryTest\"\'\n\017InstructionList\022\024\n"
          + "\014instructions\030\001 \003(\t\"g\n\006Method\022\014\n\004name\030\001 "
          + "\001(\t\022@\n\tresources\030\002 \003(\0162-.google.cloud.co"
          + "nformance.storage.v1.Resource\022\r\n\005group\030\003"
          + " \001(\t\"\344\001\n\tRetryTest\022\n\n\002id\030\001 \001(\005\022\023\n\013descri"
          + "ption\030\002 \001(\t\022C\n\005cases\030\003 \003(\01324.google.clou"
          + "d.conformance.storage.v1.InstructionList"
          + "\022<\n\007methods\030\004 \003(\0132+.google.cloud.conform"
          + "ance.storage.v1.Method\022\034\n\024preconditionPr"
          + "ovided\030\005 \001(\010\022\025\n\rexpectSuccess\030\006 \001(\010*O\n\010U"
          + "rlStyle\022\016\n\nPATH_STYLE\020\000\022\030\n\024VIRTUAL_HOSTE"
          + "D_STYLE\020\001\022\031\n\025BUCKET_BOUND_HOSTNAME\020\002*B\n\010"
          + "Resource\022\n\n\006BUCKET\020\000\022\n\n\006OBJECT\020\001\022\020\n\014NOTI"
          + "FICATION\020\002\022\014\n\010HMAC_KEY\020\003B|\n\'com.google.c"
          + "loud.conformance.storage.v1P\001Z#google/cl"
          + "oud/conformance/storage/v1\252\002)Google.Clou"
          + "d.Storage.V1.Tests.Conformanceb\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.protobuf.TimestampProto.getDescriptor(),
            });
    internal_static_google_cloud_conformance_storage_v1_TestFile_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_google_cloud_conformance_storage_v1_TestFile_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_conformance_storage_v1_TestFile_descriptor,
            new java.lang.String[] {
              "SigningV4Tests", "PostPolicyV4Tests", "RetryTests",
            });
    internal_static_google_cloud_conformance_storage_v1_SigningV4Test_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_google_cloud_conformance_storage_v1_SigningV4Test_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_conformance_storage_v1_SigningV4Test_descriptor,
            new java.lang.String[] {
              "FileName",
              "Description",
              "Bucket",
              "Object",
              "Method",
              "Expiration",
              "Timestamp",
              "ExpectedUrl",
              "Headers",
              "QueryParameters",
              "Scheme",
              "UrlStyle",
              "BucketBoundHostname",
              "ExpectedCanonicalRequest",
              "ExpectedStringToSign",
              "Hostname",
              "ClientEndpoint",
              "EmulatorHostname",
              "UniverseDomain",
            });
    internal_static_google_cloud_conformance_storage_v1_SigningV4Test_HeadersEntry_descriptor =
        internal_static_google_cloud_conformance_storage_v1_SigningV4Test_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_conformance_storage_v1_SigningV4Test_HeadersEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_conformance_storage_v1_SigningV4Test_HeadersEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_conformance_storage_v1_SigningV4Test_QueryParametersEntry_descriptor =
        internal_static_google_cloud_conformance_storage_v1_SigningV4Test_descriptor
            .getNestedTypes()
            .get(1);
    internal_static_google_cloud_conformance_storage_v1_SigningV4Test_QueryParametersEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_conformance_storage_v1_SigningV4Test_QueryParametersEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_conformance_storage_v1_ConditionalMatches_descriptor =
        getDescriptor().getMessageTypes().get(2);
    internal_static_google_cloud_conformance_storage_v1_ConditionalMatches_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_conformance_storage_v1_ConditionalMatches_descriptor,
            new java.lang.String[] {
              "Expression",
            });
    internal_static_google_cloud_conformance_storage_v1_PolicyConditions_descriptor =
        getDescriptor().getMessageTypes().get(3);
    internal_static_google_cloud_conformance_storage_v1_PolicyConditions_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_conformance_storage_v1_PolicyConditions_descriptor,
            new java.lang.String[] {
              "ContentLengthRange", "StartsWith",
            });
    internal_static_google_cloud_conformance_storage_v1_PolicyInput_descriptor =
        getDescriptor().getMessageTypes().get(4);
    internal_static_google_cloud_conformance_storage_v1_PolicyInput_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_conformance_storage_v1_PolicyInput_descriptor,
            new java.lang.String[] {
              "Scheme",
              "UrlStyle",
              "BucketBoundHostname",
              "Bucket",
              "Object",
              "Expiration",
              "Timestamp",
              "Fields",
              "Conditions",
            });
    internal_static_google_cloud_conformance_storage_v1_PolicyInput_FieldsEntry_descriptor =
        internal_static_google_cloud_conformance_storage_v1_PolicyInput_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_conformance_storage_v1_PolicyInput_FieldsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_conformance_storage_v1_PolicyInput_FieldsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_conformance_storage_v1_PolicyOutput_descriptor =
        getDescriptor().getMessageTypes().get(5);
    internal_static_google_cloud_conformance_storage_v1_PolicyOutput_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_conformance_storage_v1_PolicyOutput_descriptor,
            new java.lang.String[] {
              "Url", "Fields", "ExpectedDecodedPolicy",
            });
    internal_static_google_cloud_conformance_storage_v1_PolicyOutput_FieldsEntry_descriptor =
        internal_static_google_cloud_conformance_storage_v1_PolicyOutput_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_conformance_storage_v1_PolicyOutput_FieldsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_conformance_storage_v1_PolicyOutput_FieldsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_conformance_storage_v1_PostPolicyV4Test_descriptor =
        getDescriptor().getMessageTypes().get(6);
    internal_static_google_cloud_conformance_storage_v1_PostPolicyV4Test_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_conformance_storage_v1_PostPolicyV4Test_descriptor,
            new java.lang.String[] {
              "Description", "PolicyInput", "PolicyOutput",
            });
    internal_static_google_cloud_conformance_storage_v1_RetryTests_descriptor =
        getDescriptor().getMessageTypes().get(7);
    internal_static_google_cloud_conformance_storage_v1_RetryTests_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_conformance_storage_v1_RetryTests_descriptor,
            new java.lang.String[] {
              "RetryTests",
            });
    internal_static_google_cloud_conformance_storage_v1_InstructionList_descriptor =
        getDescriptor().getMessageTypes().get(8);
    internal_static_google_cloud_conformance_storage_v1_InstructionList_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_conformance_storage_v1_InstructionList_descriptor,
            new java.lang.String[] {
              "Instructions",
            });
    internal_static_google_cloud_conformance_storage_v1_Method_descriptor =
        getDescriptor().getMessageTypes().get(9);
    internal_static_google_cloud_conformance_storage_v1_Method_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_conformance_storage_v1_Method_descriptor,
            new java.lang.String[] {
              "Name", "Resources", "Group",
            });
    internal_static_google_cloud_conformance_storage_v1_RetryTest_descriptor =
        getDescriptor().getMessageTypes().get(10);
    internal_static_google_cloud_conformance_storage_v1_RetryTest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_conformance_storage_v1_RetryTest_descriptor,
            new java.lang.String[] {
              "Id", "Description", "Cases", "Methods", "PreconditionProvided", "ExpectSuccess",
            });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
